//go:build ignore

// Copyright (c) 2025, Oracle and/or its affiliates.
package main

import (
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// Run from tlc with the pinned sibling checkout:
// go run generate_mp.go ../../tlaplus/tlatools/org.lamport.tlatools/src/tlc2/output/MP.java ../../tlaplus/tlatools/org.lamport.tlatools/src/tlc2/output/EC.java output_mp_generated.go
// The generator accepts only the source's literal append grammar. Conditional
// cases stay in output_mp.go; unsupported source changes fail generation.
const conditionalSourceSHA256 = "3a2097ae9515d1679241472b29755584a424e6b1206858bccab30ef280fa6f3c"

var dynamic = strings.Fields(`SYSTEM_ERROR_READING_POOL SYSTEM_ERROR_CLEANING_POOL
 TLC_STATE_NOT_COMPLETELY_SPECIFIED_NEXT TLC_INVARIANT_VIOLATED_LEVEL
 TLC_INVARIANT_EVALUATION_FAILED TLC_ACTION_PROPERTY_EVALUATION_FAILED
 TLC_TEMPORAL_PROPERTY_VIOLATED TLC_BACK_TO_STATE TLC_CONFIG_ID_REQUIRES_NO_ARG
 TLC_LIVE_CANNOT_HANDLE_FORMULA TLC_MODE_MC TLC_MODE_MC_DFS TLC_MODE_SIMU
 TLC_SUCCESS TLC_PROGRESS_STATS TLC_PROGRESS_STATS_DFID TLC_PROGRESS_SIMU
 CHECK_PARAM_UNRECOGNIZED TLC_STATE_PRINT2 GENERAL`)
var javaTrivia = regexp.MustCompile(`(?s)"(?:\\.|[^"\\])*"|//[^\n]*|/\*.*?\*/`)

func clean(s string) string {
	return javaTrivia.ReplaceAllStringFunc(s, func(part string) string {
		if strings.HasPrefix(part, `"`) {
			return part
		}
		return " "
	})
}
func check(e error) {
	if e != nil {
		panic(e)
	}
}
func read(path string) string { b, e := os.ReadFile(path); check(e); return clean(string(b)) }
func main() {
	if len(os.Args) != 4 {
		panic("usage: go run generate_mp.go MP.java EC.java output.go")
	}
	mp, ec := read(os.Args[1]), read(os.Args[2])
	start := strings.Index(mp, "private static String getMessage0(")
	if start < 0 {
		panic("missing source message function")
	}
	end := strings.Index(mp[start:], "public static String getError(int errorCode)")
	if end < 0 {
		panic("missing source message function")
	}
	body := mp[start : start+end]
	intRE := regexp.MustCompile(`\bint\s+([A-Z][A-Z_0-9]*)\s*=\s*([^;]+);`)
	pending := map[string]string{}
	codes := map[string]int{}
	for _, m := range intRE.FindAllStringSubmatch(ec, -1) {
		pending[m[1]] = strings.TrimSpace(m[2])
	}
	for len(pending) > 0 {
		advanced := false
		for name, expression := range pending {
			terms := strings.Split(expression, "+")
			value := 0
			valid := true
			for _, term := range terms {
				term = strings.TrimSpace(term)
				n, e := strconv.Atoi(term)
				if e != nil {
					var ok bool
					n, ok = codes[term]
					if !ok {
						valid = false
						break
					}
				}
				value += n
			}
			if valid {
				codes[name] = value
				delete(pending, name)
				advanced = true
			}
		}
		if !advanced {
			break
		}
	}
	constRE := regexp.MustCompile(`\bString\s+([A-Z][A-Z_0-9]*)\s*=\s*("(?:\\.|[^"\\])*")\s*;`)
	constants := map[string]string{"TLAConstants.STUTTERING": " Stuttering"}
	for _, m := range constRE.FindAllStringSubmatch(mp, -1) {
		value, e := strconv.Unquote(m[2])
		check(e)
		constants[m[1]] = value
	}
	caseRE := regexp.MustCompile(`case\s+EC\.([A-Z_0-9]+)\s*:`)
	matches := caseRE.FindAllStringSubmatchIndex(body, -1)
	isDynamic := map[string]bool{}
	seen := map[string]bool{}
	for _, name := range dynamic {
		isDynamic[name] = true
	}
	var out strings.Builder
	out.WriteString("// Copyright (c) 2025, Oracle and/or its affiliates.\n// Code generated by generate_mp.go from Java MP.getMessage0; DO NOT EDIT.\npackage tlc\n\nfunc javaStaticMessageTemplate(code int) (string, bool) {\nswitch code {\n")
	count := 0
	var conditionalSource strings.Builder
	for i, m := range matches {
		name := body[m[2]:m[3]]
		seen[name] = true
		limit := len(body)
		if i+1 < len(matches) {
			limit = matches[i+1][0]
		}
		part := strings.TrimSpace(body[m[1]:limit])
		if isDynamic[name] {
			conditionalSource.WriteString(name + "\x00" + part + "\x00")
			continue
		}
		code, ok := codes[name]
		if !ok {
			panic("unresolved code: " + name)
		}
		parts, e := appends(part, constants)
		if e != nil {
			panic(name + ": " + e.Error())
		}
		if len(parts) == 0 {
			panic("no append expression: " + name)
		}
		fmt.Fprintf(&out, "case %d: // EC.%s\nreturn %s, true\n", code, name, strings.Join(parts, " + "))
		count++
	}
	if len(matches) != 245 || count != 225 {
		panic(fmt.Sprintf("source case count changed: %d cases, %d literal cases", len(matches), count))
	}
	if digest := fmt.Sprintf("%x", sha256.Sum256([]byte(conditionalSource.String()))); digest != conditionalSourceSHA256 {
		panic("conditional Java message source changed; audit output_mp.go before regeneration: " + digest)
	}
	for _, name := range dynamic {
		if !seen[name] {
			panic("missing conditional source case: " + name)
		}
	}
	out.WriteString("}\nreturn \"\", false\n}\n")
	formatted, e := format.Source([]byte(out.String()))
	check(e)
	check(os.WriteFile(os.Args[3], formatted, 0644))
	fmt.Printf("Generated %d literal templates and verified %d conditional cases from %s\n", count, len(dynamic), filepath.Base(os.Args[1]))
}
func appends(body string, constants map[string]string) ([]string, error) {
	parts := []string{}
	s := body
	for {
		s = strings.TrimSpace(s)
		if strings.HasPrefix(s, "break;") {
			s = strings.TrimSpace(strings.TrimPrefix(s, "break;"))
			if s != "" {
				return nil, fmt.Errorf("unexpected text after break: %s", s)
			}
			return parts, nil
		}
		prefix := "b.append("
		if strings.HasPrefix(s, ".append(") {
			prefix = ".append("
		}
		if !strings.HasPrefix(s, prefix) {
			return nil, fmt.Errorf("unsupported statement: %s", s)
		}
		s = s[len(prefix):]
		depth := 1
		quoted, escaped := false, false
		closing := -1
		for i, r := range s {
			if quoted {
				if escaped {
					escaped = false
				} else if r == '\\' {
					escaped = true
				} else if r == '"' {
					quoted = false
				}
				continue
			}
			if r == '"' {
				quoted = true
				continue
			}
			if r == '(' {
				depth++
			}
			if r == ')' {
				depth--
				if depth == 0 {
					closing = i
					break
				}
			}
		}
		if closing < 0 {
			return nil, fmt.Errorf("unterminated append")
		}
		expression := s[:closing]
		values, e := expressionParts(expression, constants)
		if e != nil {
			return nil, e
		}
		parts = append(parts, values...)
		s = s[closing+1:]
		s = strings.TrimSpace(s)
		if strings.HasPrefix(s, ";") {
			s = s[1:]
		}
	}
}
func expressionParts(s string, constants map[string]string) ([]string, error) {
	result := []string{}
	for {
		s = strings.TrimSpace(s)
		if s == "" {
			return result, nil
		}
		if s[0] == '"' {
			escaped := false
			closing := -1
			for i := 1; i < len(s); i++ {
				if escaped {
					escaped = false
				} else if s[i] == '\\' {
					escaped = true
				} else if s[i] == '"' {
					closing = i
					break
				}
			}
			if closing < 0 {
				return nil, fmt.Errorf("unterminated string")
			}
			value, e := strconv.Unquote(s[:closing+1])
			if e != nil {
				return nil, e
			}
			result = append(result, strconv.Quote(value))
			s = s[closing+1:]
		} else {
			closing := strings.Index(s, "+")
			if closing < 0 {
				closing = len(s)
			}
			name := strings.TrimSpace(s[:closing])
			s = s[closing:]
			if name == "now()" {
				result = append(result, "messageNow()")
			} else if value, ok := constants[name]; ok {
				result = append(result, strconv.Quote(value))
			} else {
				return nil, fmt.Errorf("unsupported expression: %s", name)
			}
		}
		s = strings.TrimSpace(s)
		if s == "" {
			return result, nil
		}
		if s[0] != '+' {
			return nil, fmt.Errorf("unexpected expression tail: %s", s)
		}
		s = s[1:]
	}
}
