// Copyright (c) 2025, Oracle and/or its affiliates.
// Code generated by generate_mp.go from Java MP.getMessage0; DO NOT EDIT.
package tlc

func javaStaticMessageTemplate(code int) (string, bool) {
	switch code {
	case -123456: // EC.UNIT_TEST
		return "[%1%][%2%]", true
	case 1005: // EC.SYSTEM_STACK_OVERFLOW
		return "This was a Java StackOverflowError. It was probably the result\n" + "of an incorrect recursive function definition that caused TLC to enter\n" + "an infinite loop when trying to compute the function or its application\n" + "to an element in its putative domain.", true
	case 1001: // EC.SYSTEM_OUT_OF_MEMORY
		return "Java ran out of memory.  Running Java with a larger memory allocation\n" + "pool (heap) may fix this.  But it won't help if some state has an enormous\n" + "number of successor states, or if TLC must compute the value of a huge set.", true
	case 1003: // EC.SYSTEM_OUT_OF_MEMORY_LIVENESS
		return "Java ran out of memory during liveness checking.  Running Java with a larger memory\n" + "allocation pool (heap) may fix this.  But it won't help if paths in the liveness graph\n" + "have an enormous number of states.", true
	case 1002: // EC.SYSTEM_OUT_OF_MEMORY_TOO_MANY_INIT
		return "Out Of Memory. There are probably too many initial states.", true
	case 2126: // EC.SYSTEM_CHECKPOINT_RECOVERY_CORRUPT
		return "TLC encountered the following error while restarting from a " + "checkpoint;\n the checkpoint file is probably corrupted.\n%1%", true
	case 2174: // EC.SYSTEM_ERROR_READING_STATES
		return "TLC encountered the following error reading the %1% of unexplored states:\n%2%", true
	case 2175: // EC.SYSTEM_ERROR_WRITING_STATES
		return "TLC encountered the following error writing the %1% of unexplored states:\n%2%", true
	case 2127: // EC.SYSTEM_ERROR_WRITING_POOL
		return "when writing the disk (StatePoolWriter.run):\n%1%", true
	case 2129: // EC.SYSTEM_DISKGRAPH_ACCESS
		return "DiskGraph.toString()", true
	case 2137: // EC.SYSTEM_FILE_NULL
		return "File must be not null", true
	case 2138: // EC.SYSTEM_INTERRUPTED
		return "Thread has been interrupted.", true
	case 2134: // EC.SYSTEM_INDEX_ERROR
		return "Index error.", true
	case 2135: // EC.SYSTEM_STREAM_EMPTY
		return "The provided input stream was null, empty or could not be accessed.", true
	case 2167: // EC.SYSTEM_UNABLE_TO_OPEN_FILE
		return "Unable to open %1%.\n%2%", true
	case 2160: // EC.SYSTEM_UNABLE_NOT_RENAME_FILE
		return "Unable not rename file during the clean-up.", true
	case 2161: // EC.SYSTEM_DISK_IO_ERROR_FOR_FILE
		return "Disk I/O error accessing the file for %1%.", true
	case 2162: // EC.SYSTEM_METADIR_EXISTS
		return "TLC writes its files to a directory whose name is generated from the current " + "time.\nThis directory should be %1%, but that directory already exists.\n" + "Trying to run TLC again will probably fix this problem.", true
	case 2163: // EC.SYSTEM_METADIR_CREATION_ERROR
		return "TLC could not make a directory %1% for the disk files it needs to write.", true
	case 2254: // EC.SYSTEM_FINGERPRINT_OVERFLOW_ERROR
		return "The requested fingerprint set size is too large, which could result in precision " + "or overflow errors. To resolve this, either increase the fingerprint size to " + "the next power of two (ensuring safe bit-shifting) or adjust the fpbits " + "parameter to a higher value.", true
	case 1102: // EC.WRONG_COMMANDLINE_PARAMS_TLC
		return "%1%\nUsage: java tlc2.TLC [-help] [-option] inputfile", true
	case 1101: // EC.WRONG_COMMANDLINE_PARAMS_SIMULATOR
		return "%1%\nUsage: java tlc2.Simulator [-help] [-option] inputfile", true
	case 2262: // EC.TLC_VERSION
		return "TLC2 %1%", true
	case 2001: // EC.TLC_PP_FORMATING_VALUE
		return "error while formating %1%\n%2%", true
	case 2000: // EC.TLC_PP_PARSING_VALUE
		return "error while parsing %1%\n%2%", true
	case 2100: // EC.TLC_METADIR_EXISTS
		return "TLC writes its files to a directory which name is generated" + " from the current time.\nThis directory should be %1%" + ", but that directory already exists.\n" + "Trying to run TLC again will probably fix this problem.\n", true
	case 2101: // EC.TLC_METADIR_CAN_NOT_BE_CREATED
		return "TLC could not make a directory for the disk files" + " it needs to write.\n", true
	case 2102: // EC.TLC_INITIAL_STATE
		return "%1%\nWhile working on the initial state:\n%2%", true
	case 2103: // EC.TLC_NESTED_EXPRESSION
		return "The error occurred when TLC was evaluating the nested" + "\nexpressions at the following positions:\n%1%", true
	case 2104: // EC.TLC_ASSUMPTION_FALSE
		return "Assumption %1% is false.", true
	case 2404: // EC.TLC_POSTCONDITION_FALSE
		return "Postcondition %1% at %2% is false.", true
	case 2780: // EC.TLC_POSSIBLE_UNWITNESSED
		return "The _POSSIBLE predicate %1% at %2% was never witnessed.\n" + "Others may be unwitnessed too; only witnessed predicates appear with a\n" + "non-zero count in the record printed above.\n" + "See https://explain.tlapl.us/possible-conditions for additional details.", true
	case 2405: // EC.TLC_POSTCONDITION_EVALUATION_ERROR
		return "Evaluating postcondition %1% at %2% failed.\n%3%", true
	case 2220: // EC.TLC_SANY_START
		return "Starting SANY...", true
	case 2219: // EC.TLC_SANY_END
		return "SANY finished.", true
	case 2105: // EC.TLC_ASSUMPTION_EVALUATION_ERROR
		return "Evaluating assumption %1% failed.\n%2%", true
	case 2106: // EC.TLC_STATE_NOT_COMPLETELY_SPECIFIED_INITIAL
		return "State is not completely specified by the initial predicate:\n%1%", true
	case 2107: // EC.TLC_INVARIANT_VIOLATED_INITIAL
		return "Invariant %1% is violated by the initial state:\n%2%", true
	case 2108: // EC.TLC_PROPERTY_VIOLATED_INITIAL
		return "Property %1% is violated by the initial state:\n%2%", true
	case 2148: // EC.TLC_STATE_NOT_COMPLETELY_SPECIFIED_LIVE
		return "The action formula A appearing in a WF_v(A) or SF_v(A) operator does not specify the primed value of the variable %1% occurring in the state formula v.\n", true
	case 2110: // EC.TLC_INVARIANT_VIOLATED_BEHAVIOR
		return "Invariant %1% is violated.", true
	case 2149: // EC.TLC_INVARIANT_CONSTANT_LEVEL
		return "The invariant %1% is a constant-level formula (i.e., it contains no variables, primes, or temporal operators) and evaluates to %2%. " + "To assert constant-level formulas in your spec, use ASSUME ConstInv. If you optionally want to give the assumption a name, write ASSUME YourAssumption == ConstInv instead. " + "See https://explain.tlapl.us/assumptions-and-invariants for additional details.", true
	case 2112: // EC.TLC_ACTION_PROPERTY_VIOLATED_BEHAVIOR
		return "Action property %1%" + " is violated.", true
	case 2114: // EC.TLC_DEADLOCK_REACHED
		return "Deadlock reached.", true
	case 2264: // EC.TLC_COUNTER_EXAMPLE
		return "The following behavior constitutes a counter-example:\n", true
	case 2115: // EC.TLC_STATES_AND_NO_NEXT_ACTION
		return "No next state actions defined to generate successor states from.", true
	case 2117: // EC.TLC_FAILED_TO_RECOVER_NEXT
		return "Failed to recover the next state from its fingerprint.", true
	case 2123: // EC.TLC_FAILED_TO_RECOVER_INIT
		return "Failed to recover the initial state from its fingerprint.", true
	case 2128: // EC.TLC_BUG
		return "This is probably a TLC bug(%1%).", true
	case 2147: // EC.TLC_FINGERPRINT_EXCEPTION
		return "TLC was unable to fingerprint." + "\n" + "\nFingerprint Stack Trace:" + "\n%1%" + "\nReason:" + "\n%2%", true
	case 2118: // EC.TLC_NO_STATES_SATISFYING_INIT
		return "There is no state satisfying the initial state predicate.", true
	case 2256: // EC.TLC_NO_STATES_SATISFYING_INIT_AND_CONSTRAINT
		return "There is no state satisfying the initial state predicate and the state-constraint(s).", true
	case 2119: // EC.TLC_STRING_MODULE_NOT_FOUND
		return "This is a TLC bug: TLC could not find its built-in String module.\n", true
	case 2120: // EC.TLC_ERROR_STATE
		return "The error state is:\n", true
	case 2121: // EC.TLC_BEHAVIOR_UP_TO_THIS_POINT
		return "The behavior up to this point is:", true
	case 2124: // EC.TLC_REPORTER_DIED
		return "Progress report thread died.", true
	case 2130: // EC.TLC_AAAAAAA
		return "AAAAAA", true
	case 2131: // EC.TLC_REGISTRY_INIT_ERROR
		return "TLA+ Registry initialization error. The name %1% is already in use.", true
	case 3000: // EC.CHECK_FAILED_TO_CHECK
		return "TLC failed in checking traces.", true
	case 3101: // EC.CHECK_PARAM_USAGE
		return "Usage: java tlc2.tool.CheckImplFile [-option] inputfile", true
	case 3102: // EC.CHECK_PARAM_MISSING_TLA_MODULE
		return "Missing input TLA+ module.", true
	case 3100: // EC.CHECK_PARAM_EXPECT_CONFIG_FILENAME
		return "Expect a file name for -config option.", true
	case 3103: // EC.CHECK_PARAM_NEED_TO_SPECIFY_CONFIG_DIR
		return "need to specify the metadata directory for recovery.", true
	case 3104: // EC.CHECK_PARAM_WORKER_NUMBER_REQUIRED
		return "Worker number required. But encountered %1%", true
	case 3105: // EC.CHECK_PARAM_WORKER_NUMBER_TOO_SMALL
		return "At least one worker is required.", true
	case 3106: // EC.CHECK_PARAM_WORKER_NUMBER_REQUIRED2
		return "Expect an integer for -workers option.", true
	case 3107: // EC.CHECK_PARAM_DEPTH_REQUIRED
		return "Depth must be an integer. But encountered %1%", true
	case 3108: // EC.CHECK_PARAM_DEPTH_REQUIRED2
		return "Expect an integer for -depth option.", true
	case 3109: // EC.CHECK_PARAM_TRACE_REQUIRED
		return "Expect a filename for -trace option.", true
	case 3110: // EC.CHECK_PARAM_COVREAGE_REQUIRED
		return "An integer for coverage report interval required. But encountered %1%", true
	case 3111: // EC.CHECK_PARAM_COVREAGE_REQUIRED2
		return "Coverage report interval required.", true
	case 3112: // EC.CHECK_PARAM_COVREAGE_TOO_SMALL
		return "Expect a nonnegative integer for -coverage option.", true
	case 3114: // EC.CHECK_PARAM_TOO_MANY_INPUT_FILES
		return "More than one input files: %1% and %2%", true
	case 3001: // EC.CHECK_COULD_NOT_READ_TRACE
		return "TLC could not read in the trace. %1%", true
	case 3002: // EC.TLC_PARSING_FAILED
		return "Parsing or semantic analysis failed.", true
	case 2171: // EC.TLC_PARSING_FAILED2
		return "Parsing or semantic analysis failed.%1%", true
	case 2132: // EC.TLC_VALUE_ASSERT_FAILED
		return "The first argument of Assert evaluated to FALSE; the second argument was:\n%1%", true
	case 2133: // EC.TLC_FP_NOT_IN_SET
		return "The fingerprint is not in set.", true
	case 2211: // EC.TLC_FP_COMPLETED
		return "%1%, work completed. Thank you!", true
	case 2136: // EC.TLC_PARAMETER_MUST_BE_POSTFIX
		return "Parameter must be a postfix operator", true
	case 2139: // EC.TLC_COULD_NOT_DETERMINE_SUBSCRIPT
		return "TLC could not determine if the subscript of the next-state relation contains" + "\nall state variables. Proceed with fingers crossed.", true
	case 2140: // EC.TLC_SUBSCRIPT_CONTAIN_NO_STATE_VAR
		return "The subscript of the next-state relation specified by the specification" + "\ndoes not seem to contain the state variable %1%", true
	case 2141: // EC.TLC_WRONG_TUPLE_FIELD_NAME
		return "Tuple field name %1% is not an integer.", true
	case 2142: // EC.TLC_WRONG_RECORD_FIELD_NAME
		return "Record field name %1% is not a string.", true
	case 2143: // EC.TLC_UNCHANGED_VARIABLE_CHANGED
		return "The variable %1% was changed while it is specified as UNCHANGED at\n%2%", true
	case 2144: // EC.TLC_EXCEPT_APPLIED_TO_UNKNOWN_FIELD
		return "The EXCEPT was applied to non-existing fields of the value at\n%1%", true
	case 2300: // EC.TLC_SYMMETRY_SET_TOO_SMALL
		return "The set%1% %2% %3% been defined to be a symmetry set but contain%4% less than two elements.", true
	case 2301: // EC.TLC_SPECIFICATION_FEATURES_TEMPORAL_QUANTIFIER
		return "TLC does not support temporal existential, nor universal, quantification over state variables.", true
	case 2145: // EC.TLC_MODULE_TLCGET_UNDEFINED
		return "TLCGet(%1%) was undefined.", true
	case 2178: // EC.TLC_MODULE_OVERFLOW
		return "Overflow when computing %1%", true
	case 2283: // EC.TLC_MODULE_ONE_ARGUMENT_ERROR
		return "The argument of %1% should be a %2%, but instead it is:\n%3%", true
	case 2169: // EC.TLC_MODULE_ARGUMENT_ERROR
		return "The %1% argument of %2% should be a %3%, but instead it is:\n%4%", true
	case 2266: // EC.TLC_MODULE_ARGUMENT_ERROR_AN
		return "The %1% argument of %2% should be an %3%, but instead it is:\n%4%", true
	case 2183: // EC.TLC_MODULE_ARGUMENT_NOT_IN_DOMAIN
		return "The %1% argument of %2% must be in the domain of its %3% argument:\n%4%\n, but" + " instead it is\n%5%", true
	case 2179: // EC.TLC_MODULE_DIVISION_BY_ZERO
		return "The second argument of \\div is 0.", true
	case 2180: // EC.TLC_MODULE_NULL_POWER_NULL
		return "0^0 is undefined.", true
	case 2176: // EC.TLC_MODULE_APPLYING_TO_WRONG_VALUE
		return "Applying %1% to the following value,\nwhich is not %2%:\n%3%", true
	case 2155: // EC.TLC_MODULE_COMPARE_VALUE
		return "Attempted to compare %1% with the value\n%2%", true
	case 2184: // EC.TLC_MODULE_APPLY_EMPTY_SEQ
		return "Attempted to apply %1% to the empty sequence.", true
	case 2158: // EC.TLC_MODULE_CHECK_MEMBER_OF
		return "Attempted to check if the value:\n%1%\nis an element of %2%.", true
	case 2177: // EC.TLC_MODULE_BAG_UNION1
		return "Attempted to apply BagUnion to the following set, whose\nelement is not a bag:\n%1%", true
	case 2157: // EC.TLC_MODULE_TRANSITIVE_CLOSURE
		return "Attempted to apply TransitiveClosure to a set containing\nthe following value:\n%1%", true
	case 2181: // EC.TLC_MODULE_COMPUTING_CARDINALITY
		return "Attempted to compute cardinality of the value\n%1%", true
	case 2182: // EC.TLC_MODULE_EVALUATING
		return "Evaluating an expression of the form %1% when s is not a %2%:\n%3%", true
	case 2154: // EC.TLC_MODULE_VALUE_JAVA_METHOD_OVERRIDE
		return "Attempted to apply the operator overridden by the Java method" + "\n%1%,\nbut it produced the following error:\n%2%", true
	case 2168: // EC.TLC_MODULE_VALUE_JAVA_METHOD_OVERRIDE_LOADED
		return "Loading %1% operator override from %2% with signature: %3%.", true
	case 2400: // EC.TLC_MODULE_VALUE_JAVA_METHOD_OVERRIDE_MISMATCH
		return "Failed to match %1% operator override from %2% with signature: %3%.", true
	case 2403: // EC.TLC_MODULE_VALUE_JAVA_METHOD_OVERRIDE_IDENTIFIER_MISMATCH
		return "Failed to match %1% operator override from %2% with signature: %3% (no such operator).", true
	case 2402: // EC.TLC_MODULE_VALUE_JAVA_METHOD_OVERRIDE_MODULE_MISMATCH
		return "Failed to match %1% operator override from %2% with signature: %3% (no such module).", true
	case 20000: // EC.TLC_MODULE_OVERRIDE_STDOUT
		return "%1%", true
	case 2156: // EC.TLC_FEATURE_UNSUPPORTED
		return "%1%", true
	case 2279: // EC.TLC_FEATURE_UNSUPPORTED_LIVENESS_SYMMETRY
		return "Declaring symmetry during liveness checking is dangerous. " + "It might cause TLC to miss violations of the stated liveness properties. " + "Please check liveness without symmetry defined.", true
	case 2284: // EC.TLC_FEATURE_LIVENESS_CONSTRAINTS
		return "Declaring state or action constraints during liveness checking is dangerous: " + "Please read section 14.3.5 on page 247 of Specifying Systems " + "(https://lamport.azurewebsites.net/tla/book.html) and optionally the " + "discussion at https://discuss.tlapl.us/msg00994.html for more details.", true
	case 2159: // EC.TLC_LIVE_BEGRAPH_FAILED_TO_CONSTRUCT
		return "BEGraph.GetPath: Failed to construct a path.", true
	case 2212: // EC.TLC_LIVE_IMPLIED
		return "Implied-temporal checking--satisfiability problem has %1% branches.", true
	case 2263: // EC.TLC_LIVE_IMPLIED_DEBUG
		return "Implied-temporal checking--branch of satisfiable problem has %1% possible error model(s), %2% promise(s), %3% state check(s), %4% action check(s), and a tableau with %5% node(s).", true
	case 2214: // EC.TLC_LIVE_WRONG_FORMULA_FORMAT
		return "Temporal formulas containing actions must be of forms <>[]A or []<>A.", true
	case 2249: // EC.TLC_LIVE_ENCOUNTERED_ACTIONS
		return "TLC encountered actions when computing closure.", true
	case 2250: // EC.TLC_LIVE_STATE_PREDICATE_NON_BOOL
		return "A state predicate was evaluated to a non-boolean value.", true
	case 2251: // EC.TLC_LIVE_CANNOT_EVAL_FORMULA
		return "Can not evaluate a temporal formula %1%F.", true
	case 2252: // EC.TLC_LIVE_ENCOUNTERED_NONBOOL_PREDICATE
		return "Encountered an action predicate that's not a boolean.", true
	case 2253: // EC.TLC_LIVE_FORMULA_TAUTOLOGY
		return "Temporal formula is a tautology (its negation is unsatisfiable).", true
	case 2258: // EC.TLC_LIVE_FORMULA_AND_FAIRNESS_TAUTOLOGY
		return "Implied-temporal checking is a tautology.\n" + "The temporal formula %1% at %2% equals\n" + "the fairness constraints of the behavior specification %3% at %4%.\n" + "Therefore, checking whether %3% => %1% using TLC will never result in a violation of %1%.", true
	case 2255: // EC.TLC_LIVE_FORMULA_STATE_LEVEL
		return "The formula %1% is a state-level formula, but it was used as a PROPERTY (or PROPERTIES), " + "where a temporal formula is typically expected. State-level formulas used as PROPERTY " + "or PROPERTIES are only checked in the initial state. To verify that the formula %1% " + "holds in all states of every behavior, use INVARIANT %1% instead. Alternatively, " + "applying the \"always\" temporal operator ([]) to the state-level formula %1% changes it " + "into a temporal formula, asserting that %1% holds in all states of every behavior. " + "See https://explain.tlapl.us/invariants-and-properties for additional details.", true
	case 2257: // EC.TLC_CONFIG_NO_SPEC_BUT_PROPERTY
		return "The stuttering counterexample above may be caused by the absence of a behavior specification " + "(SPECIFICATION). Only INIT and NEXT have been provided, so TLC permits infinite stuttering. " + "To rule out such counterexamples, use SPECIFICATION Spec, with Spec asserting a suitable fairness " + "constraint (compare Chapter 8, page 87ff of Specifying Systems at " + "https://lamport.azurewebsites.net/tla/book.html).", true
	case 2259: // EC.TLC_CONFIG_NO_FAIRNESS_BUT_LIVE_PROPERTY
		return "The stuttering counterexample above may be caused by the absence of a fairness constraint " + "in the behavior specification %1% defined at %2%. To rule out such counterexamples, conjoin a " + "suitable fairness constraint to %1% (compare Chapter 8, page 87ff of Specifying Systems at " + "https://lamport.azurewebsites.net/tla/book.html).", true
	case 2215: // EC.TLC_EXPECTED_VALUE
		return "TLC expected a %1% value, but did not find one. %2%", true
	case 2246: // EC.TLC_EXPECTED_EXPRESSION
		return "TLC expected a %1% expression, but did not find one.\n%2%", true
	case 2247: // EC.TLC_EXPECTED_EXPRESSION_IN_COMPUTING
		return "In computing %1%, TLC expected a %2% expression," + "\nbut instead found %3%.\n%4%", true
	case 2248: // EC.TLC_EXPECTED_EXPRESSION_IN_COMPUTING2
		return "In computing %1%, TLC expected a %2% expression," + "\nbut didn't find one.\n%3%", true
	case 2164: // EC.TLC_CHOOSE_ARGUMENTS_WRONG
		return "The arguments to %1% are not appropriate.", true
	case 2165: // EC.TLC_CHOOSE_UPPER_BOUND
		return "Choose can only deal with numbers up to %1%", true
	case 2166: // EC.TLC_FP_VALUE_ALREADY_ON_DISK
		return "DiskFPSet.mergeNewEntries: %1% is already on disk.\n", true
	case 4000: // EC.SANY_PARSER_CHECK_1
		return "TLA+ Parser sanity check.", true
	case 4001: // EC.SANY_PARSER_CHECK_2
		return "TLA+ Parser check: Assertion error in epa().", true
	case 4002: // EC.SANY_PARSER_CHECK_3
		return "TLA+ Parser check: Assertion error in SBracketCases().", true
	case 2170: // EC.TLC_ARGUMENT_MISMATCH
		return "Argument mismatch in operator application.%1", true
	case 2172: // EC.TLC_TOO_MNY_POSSIBLE_STATES
		return "Too many possible next states for the last state in the trace.", true
	case 2173: // EC.TLC_ERROR_REPLACING_MODULES
		return "Found a Java class for module %1%, but unable to read\n" + "it as a Java class object. %2%", true
	case 7000: // EC.TLC_DISTRIBUTED_SERVER_RUNNING
		return "TLC server at %1% is ready (" + messageNow() + ")", true
	case 7001: // EC.TLC_DISTRIBUTED_WORKER_REGISTERED
		return "Registration for worker at %1% completed (" + messageNow() + ")", true
	case 7002: // EC.TLC_DISTRIBUTED_WORKER_DEREGISTERED
		return "TLC worker %1% disconnected (" + messageNow() + ")", true
	case 7003: // EC.TLC_DISTRIBUTED_WORKER_STATS
		return "Worker: %1% Sent: %2% Rcvd: %3% CacheRatio: %4% (" + messageNow() + ")", true
	case 7004: // EC.TLC_DISTRIBUTED_SERVER_NOT_RUNNING
		return "TLCServer is gone due to %1%, exiting worker... (" + messageNow() + ")", true
	case 7010: // EC.TLC_DISTRIBUTED_SERVER_FINISHED
		return "TLCServer has finished, exiting worker... (" + messageNow() + ")", true
	case 7005: // EC.TLC_DISTRIBUTED_VM_VERSION
		return "VM does not allow to get the UnicastRef port.\nWorker will be identified with port 0 in output (" + messageNow() + ")", true
	case 7006: // EC.TLC_DISTRIBUTED_WORKER_LOST
		return "TLC worker connection lost %1% (" + messageNow() + ")", true
	case 7007: // EC.TLC_DISTRIBUTED_EXCEED_BLOCKSIZE
		return "Trying to limit max block size (to recover from transport failure): %1% (" + messageNow() + ")", true
	case 7009: // EC.TLC_DISTRIBUTED_SERVER_FPSET_REGISTERED
		return "%1% out of %2% FPSet server(s) registered (" + messageNow() + ")", true
	case 7008: // EC.TLC_DISTRIBUTED_SERVER_FPSET_WAITING
		return "Waiting for %1% FPSet server(s) to register (" + messageNow() + ")", true
	case 2185: // EC.TLC_STARTING
		return "Starting... (" + messageNow() + ")", true
	case 2186: // EC.TLC_FINISHED
		return "Finished in %1% at (" + messageNow() + ")", true
	case 2189: // EC.TLC_COMPUTING_INIT
		return "Computing initial states...", true
	case 2269: // EC.TLC_COMPUTING_INIT_PROGRESS
		return "Computed %1% initial states...", true
	case 2190: // EC.TLC_INIT_GENERATED1
		return "Finished computing initial states: %1% distinct state%2% generated at " + messageNow() + ".", true
	case 2191: // EC.TLC_INIT_GENERATED2
		return "Finished computing initial states: %1% state%2% generated, with %3% of them distinct at " + messageNow() + ".", true
	case 2207: // EC.TLC_INIT_GENERATED3
		return "Finished computing initial states: %1% states generated.\n" + "Because TLC recovers from a previous checkpoint, only %2% of them require further exploration at " + messageNow() + ".", true
	case 2208: // EC.TLC_INIT_GENERATED4
		return "Finished computing initial states: %1% states generated, with %2% of them distinct.", true
	case 2192: // EC.TLC_CHECKING_TEMPORAL_PROPS
		return "Checking %3%temporal properties for the %1% state space with %2% total distinct states at (" + messageNow() + ")", true
	case 2267: // EC.TLC_CHECKING_TEMPORAL_PROPS_END
		return "Finished checking temporal properties in %1% at " + messageNow(), true
	case 2194: // EC.TLC_SEARCH_DEPTH
		return "The depth of the complete state graph search is %1%.", true
	case 2268: // EC.TLC_STATE_GRAPH_OUTDEGREE
		return "The average outdegree of the complete state graph is %2% (minimum is %1%, the maximum %4% and the 95th percentile is %3%).", true
	case 2195: // EC.TLC_CHECKPOINT_START
		return "Checkpointing of run %1%", true
	case 2196: // EC.TLC_CHECKPOINT_END
		return "Checkpointing completed at (" + messageNow() + ")", true
	case 2197: // EC.TLC_CHECKPOINT_RECOVER_START
		return "Starting recovery from checkpoint %1%", true
	case 2198: // EC.TLC_CHECKPOINT_RECOVER_END
		return "Recovery completed. %1% states examined. %2% states on queue.", true
	case 2203: // EC.TLC_CHECKPOINT_RECOVER_END_DFID
		return "Recovery completed. %1% states examined.", true
	case 2199: // EC.TLC_STATS
		return "%1% states generated, %2% distinct states found, %3% states left on queue.", true
	case 2204: // EC.TLC_STATS_DFID
		return "%1% states generated, %2% distinct states found.", true
	case 2210: // EC.TLC_STATS_SIMU
		return "The number of states generated: %1%\nSimulation using seed %2% and aril %3%", true
	case 2205: // EC.TLC_PROGRESS_START_STATS_DFID
		return "Starting level %1%: %2% states generated, %3% distinct states found.", true
	case 2201: // EC.TLC_COVERAGE_START
		return "The coverage statistics at " + messageNow() + " (see https://explain.tlapl.us/module-coverage-statistics for how to interpret the following statistics).", true
	case 2221: // EC.TLC_COVERAGE_VALUE
		return "  %1%: %2%", true
	case 2775: // EC.TLC_COVERAGE_VALUE_COST
		return "  %1%: %2%:%3%", true
	case 2779: // EC.TLC_COVERAGE_VAR
		return "<%1% %2%>: %3%", true
	case 2773: // EC.TLC_COVERAGE_INIT
		return "%1%: %2%:%3%", true
	case 2772: // EC.TLC_COVERAGE_NEXT
		return "%1%: %2%:%3%", true
	case 2778: // EC.TLC_COVERAGE_CONSTRAINT
		return "%1%: %2%:%3%", true
	case 2774: // EC.TLC_COVERAGE_PROPERTY
		return "%1%", true
	case 2776: // EC.TLC_COVERAGE_MISMATCH
		return "CostModel lookup failed for expression <%1%>. Reporting costs into <%2%> instead (Safety and Liveness checking is unaffected. Please report a bug.)", true
	case 2202: // EC.TLC_COVERAGE_END
		return "End of statistics.", true
	case 2777: // EC.TLC_COVERAGE_END_OVERHEAD
		return "End of statistics (please note that for performance reasons large models\n" + "are best checked with coverage and cost statistics disabled).", true
	case 2222: // EC.TLC_CONFIG_VALUE_NOT_ASSIGNED_TO_CONSTANT_PARAM
		return "The constant parameter %1% is not assigned a value by the configuration file.", true
	case 2223: // EC.TLC_CONFIG_RHS_ID_APPEARED_AFTER_LHS_ID
		return "In the configuration file, the identifier %1% appears\n" + "on the right-hand side of a <- after already appearing on the\n" + "left-hand side of one.", true
	case 2224: // EC.TLC_CONFIG_WRONG_SUBSTITUTION
		return "The configuration file substitutes for %1% with the undefined identifier %2%.", true
	case 2280: // EC.TLC_CONFIG_UNDEFINED_OR_NO_OPERATOR
		return "In evaluation, the identifier %1% is either undefined or not an operator.\n%2%", true
	case 2281: // EC.TLC_CONFIG_SUBSTITUTION_NON_CONSTANT
		return "The configuration file substitutes constant %1% with non-constant %2%%3%", true
	case 2225: // EC.TLC_CONFIG_WRONG_SUBSTITUTION_NUMBER_OF_ARGS
		return "The configuration file substitutes for %1% with %2% of different number of arguments.", true
	case 2226: // EC.TLC_CONFIG_ID_DOES_NOT_APPEAR_IN_SPEC
		return "In the configuration file, the identifier %1% does not appear in the specification.", true
	case 2227: // EC.TLC_CONFIG_NOT_BOTH_SPEC_AND_INIT
		return "The configuration file cannot specify both INIT/NEXT and SPECIFICATION fields.", true
	case 2229: // EC.TLC_CONFIG_SPECIFIED_NOT_DEFINED
		return "The %1% %2% specified in the configuration file" + "\nis not defined in the specification.", true
	case 2230: // EC.TLC_CONFIG_ID_HAS_VALUE
		return "The %1% of %2% is equal to %3%", true
	case 2231: // EC.TLC_CONFIG_MISSING_INIT
		return "The configuration file did not specify the initial state predicate.", true
	case 2232: // EC.TLC_CONFIG_MISSING_NEXT
		return "The configuration file did not specify the next state predicate.", true
	case 2233: // EC.TLC_CONFIG_ID_MUST_NOT_BE_CONSTANT
		return "The %1% %2% cannot be a constant.", true
	case 2234: // EC.TLC_CONFIG_OP_NO_ARGS
		return "The operator %1% cannot take any argument.", true
	case 2235: // EC.TLC_CONFIG_OP_NOT_IN_SPEC
		return "The operator %1% is not defined in the spec.", true
	case 2236: // EC.TLC_CONFIG_OP_IS_EQUAL
		return "The operator %1%, which equals %2%,\ncannot be used as a %3%", true
	case 2237: // EC.TLC_CONFIG_SPEC_IS_TRIVIAL
		return "The spec is trivially false because %1% is false.", true
	case 2238: // EC.TLC_CANT_HANDLE_SUBSCRIPT
		return "TLC cannot handle subscript %1%", true
	case 2239: // EC.TLC_CANT_HANDLE_CONJUNCT
		return "TLC cannot handle this conjunct of the spec:\n%1%", true
	case 2240: // EC.TLC_CANT_HANDLE_TOO_MANY_NEXT_STATE_RELS
		return "The specification contains more than one conjunct of the form [][Next]_v," + "\nbut TLC can handle only specifications with one next-state relation.", true
	case 2282: // EC.TLC_TRACE_TOO_LONG
		return "The specification contains one or more behaviors with 65536 or more states," + "\nbut TLC can only handle behaviors of length up to 65535 states. The last\n" + "state in the behavior is:\n%1%", true
	case 2273: // EC.TLC_CONFIG_PROPERTY_ACTION_LEVEL_SQUARE_A_SUB_V
		return "The formula %1% at %2% is an action-level formula (i.e., it contains no temporal operators). " + "Only temporal-level (or state-level) formulas are allowed under PROPERTY or PROPERTIES. " + "To check that action %1% holds in *every* step of the behavior, define a temporal property " + "by applying the \"always\" temporal operator ([]) to the formula at %2% (compare page 90 of " + "Specifying Systems at https://lamport.azurewebsites.net/tla/book.html).", true
	case 2274: // EC.TLC_CONFIG_PROPERTY_ACTION_LEVEL_ANGLE_A_SUB_V
		return "The formula %1% at %2% is an action-level formula (i.e., it contains no temporal operators). " + "Only temporal-level (or state-level) formulas are allowed under PROPERTY or PROPERTIES. " + "To check that infinitely many %1% steps occur, define a temporal property by applying " + "the \"always eventually\" temporal operator combination ([]<>) to the formula at " + "%2% (compare page 91 of Specifying Systems at https://lamport.azurewebsites.net/tla/book.html).", true
	case 2272: // EC.TLC_CONFIG_PROPERTY_ACTION_LEVEL
		return "The formula %1% at %2% is an action-level formula (i.e., it contains no temporal operators). " + "Only temporal-level (or state-level) formulas are allowed under PROPERTY or PROPERTIES. " + "To check that action %1% holds in *every* step of the behavior, define a temporal property: " + "Let A be the formula at %2%; rewrite A as [][A]_v, where v is a state function (typically " + "the tuple of variables) (compare page 90 of Specifying Systems at " + "https://lamport.azurewebsites.net/tla/book.html).", true
	case 2241: // EC.TLC_CONFIG_PROPERTY_NOT_CORRECTLY_DEFINED
		return "The property %1% is not correctly defined.", true
	case 2242: // EC.TLC_CONFIG_OP_ARITY_INCONSISTENT
		return "The arity of the operator %1% is inconsistent in the configuration file.", true
	case 2243: // EC.TLC_CONFIG_NO_STATE_TYPE
		return "The configuration file did not specify types for state variables.", true
	case 2244: // EC.TLC_CANT_HANDLE_REAL_NUMBERS
		return "TLC can't handle real numbers.\n%1%", true
	case 2265: // EC.TLC_INTEGER_TOO_BIG
		return "TLC can't handle a number this big.\n%1%", true
	case 2245: // EC.TLC_NO_MODULES
		return "In the configuration file, the module name %1% is not a module in the specification.", true
	case 2260: // EC.TLC_ENABLED_WRONG_FORMULA
		return "In computing ENABLED, TLC encountered a temporal formula (%1%).\n%2%", true
	case 2261: // EC.TLC_ENCOUNTERED_FORMULA_IN_PREDICATE
		return "TLC encountered a temporal formula (%1%) when evaluating" + " a predicate or action.\n%2%", true
	case 2401: // EC.TLC_ENVIRONMENT_JVM_GC
		return "Please run the Java VM, which executes TLC with a throughput optimized garbage collector, by passing the \"-XX:+UseParallelGC\" property.", true
	case 2216: // EC.TLC_STATE_PRINT1
		return "%1%:\n%2%", true
	case 2218: // EC.TLC_STATE_PRINT3
		return "%1%:" + " Stuttering", true
	case 2501: // EC.TLC_TE_SPEC_GENERATION_COMPLETE
		return "Trace exploration spec path: %1%", true
	case 2502: // EC.TLC_TE_SPEC_GENERATION_ERROR
		return "Failed to generate trace exploration spec; error message: %1%", true
	case 5003: // EC.CFG_MISSING_ID
		return "TLC found an error in the configuration file at line %1%\n" + "The keyword %2% was not followed by an identifier.", true
	case 5004: // EC.CFG_TWICE_KEYWORD
		return "TLC found an error in the configuration file at line %1%\n" + "The keyword %2% appeared twice.", true
	case 5005: // EC.CFG_EXPECT_ID
		return "TLC found an error in the configuration file at line %1%\n" + "Expected an identifier after %2%.", true
	case 5002: // EC.CFG_GENERAL
		return "TLC found an error in the configuration file at line %1%\n", true
	case 5006: // EC.CFG_EXPECTED_SYMBOL
		return "TLC found an error in the configuration file at line %1%\n" + "It was expecting %2%, but did not find it.", true
	case 5001: // EC.CFG_ERROR_READING_FILE
		return "TLC encountered the following error when trying to read the configuration file %1%:\n%2%", true
	}
	return "", false
}
