//go:build ignore

// Regenerate with: go run sany_generate_lookahead.go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	source := "../tlaplus/tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParser.java"
	target := "sany_lookahead_generated.go"
	if len(os.Args) > 1 {
		source = os.Args[1]
	}
	if len(os.Args) > 2 {
		target = os.Args[2]
	}
	data, err := os.ReadFile(source)
	must(err)
	constants, err := os.ReadFile(filepath.Join(filepath.Dir(source), "TLAplusParserConstants.java"))
	must(err)
	values := map[string]string{}
	for _, m := range regexp.MustCompile(`\bint\s+(\w+)\s*=\s*(\d+)\s*;`).FindAllStringSubmatch(string(constants), -1) {
		values[m[1]] = m[2]
	}
	text := string(data)
	methods := map[string]string{}
	order := []string{}
	re := regexp.MustCompile(`final private boolean (jj_3(?:R)?_\d+)\(\) \{`)
	for _, m := range re.FindAllStringSubmatchIndex(text, -1) {
		name := text[m[2]:m[3]]
		depth, end := 1, m[1]
		for depth > 0 {
			if text[end] == '{' {
				depth++
			}
			if text[end] == '}' {
				depth--
			}
			end++
		}
		methods[name] = text[m[1] : end-1]
		order = append(order, name)
	}
	calls := regexp.MustCompile(`\b(jj_3(?:R)?_\d+)\(\)`)
	needed := map[string]bool{}
	var include func(string)
	include = func(name string) {
		if needed[name] {
			return
		}
		body, ok := methods[name]
		if !ok {
			panic("Missing source scanner: " + name)
		}
		needed[name] = true
		for _, m := range calls.FindAllStringSubmatch(body, -1) {
			include(m[1])
		}
	}
	// Include all JavaCC entry points and their complete dependency closure.
	for production := 1; production <= 74; production++ {
		include(fmt.Sprintf("jj_3_%d", production))
	}
	scans := regexp.MustCompile(`jj_scan_token\((\w+)\)`)
	restore := regexp.MustCompile(`if \((.*)\) s.position = xsp;`)
	early := regexp.MustCompile(`if \((.*)\) return true;`)
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by sany_generate_lookahead.go; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Source: %s\n\npackage tlago\n\n", filepath.ToSlash(filepath.Join(filepath.Base(filepath.Dir(source)), filepath.Base(source))))
	predicates := regexp.MustCompile(`(?s)lookingAhead = true;\s*jj_semLA = (.*?);\s*lookingAhead = false;`)
	token := regexp.MustCompile(`getToken\((\d+)\)`)
	words := regexp.MustCompile(`\b[A-Z][A-Z0-9_]*\b`)
	count := 0
	for _, name := range order {
		if !needed[name] {
			continue
		}
		body := methods[name]
		if strings.Contains(body, "jj_semLA") {
			body = "\nvar semLA bool\n" + body
			body = predicates.ReplaceAllStringFunc(body, func(block string) string {
				expression := predicates.FindStringSubmatch(block)[1]
				expression = strings.ReplaceAll(expression, `!getToken(1).image.equals("@")`, `getToken(1).Image != "@"`)
				expression = strings.ReplaceAll(expression, `getToken(1).image.equals("@")`, `getToken(1).Image == "@"`)
				expression = token.ReplaceAllString(expression, "s.token($1)")
				expression = strings.ReplaceAll(expression, ".kind", ".Kind")
				expression = strings.ReplaceAll(expression, ".beginColumn", ".Begin.Column")
				expression = strings.ReplaceAll(expression, "junctionListCtx.isAboveCurrent", "s.parser.junctionListContext.isAboveCurrent")
				expression = strings.ReplaceAll(expression, "matchFcnConst()", "s.matchFcnConst()")
				expression = strings.ReplaceAll(expression, "OperatorStack.preInEmptyTop()", "s.preInEmptyTop()")
				expression = strings.ReplaceAll(expression, "isFieldNameToken( s.token(1))", "isSanyFieldNameToken(s.token(1).Kind)")
				expression = words.ReplaceAllStringFunc(expression, func(word string) string {
					if value, ok := values[word]; ok {
						return "SanyTokenKind(" + value + ")"
					}
					return word
				})
				expression = strings.Join(strings.Fields(expression), " ")
				return "semLA = " + expression
			})
			body = strings.ReplaceAll(body, "jj_semLA", "semLA")
			if strings.Contains(body, "lookingAhead") {
				panic("Unconverted predicate in " + name)
			}
		}
		withoutScanSave := strings.ReplaceAll(strings.ReplaceAll(body, "Token xsp;", ""), "xsp = jj_scanpos;", "")
		if !regexp.MustCompile(`\bxsp\b`).MatchString(withoutScanSave) {
			body = withoutScanSave
		} else {
			body = strings.ReplaceAll(body, "Token xsp;", "var xsp int")
		}
		body = strings.ReplaceAll(body, "jj_scanpos", "s.position")
		body = strings.ReplaceAll(body, "while (true)", "for")
		body = scans.ReplaceAllStringFunc(body, func(call string) string {
			value := scans.FindStringSubmatch(call)[1]
			if _, err := strconv.Atoi(value); err != nil {
				var ok bool
				value, ok = values[value]
				if !ok {
					panic("Unknown token in " + call)
				}
			}
			return "s.scanToken(SanyTokenKind(" + value + "))"
		})
		body = calls.ReplaceAllString(body, "s.$1()")
		body = restore.ReplaceAllString(body, "if ($1) { s.position = xsp }")
		body = early.ReplaceAllString(body, "if ($1) { return true }")
		fmt.Fprintf(&out, "func (s *sanyLookahead) %s() bool {%s}\n\n", name, body)
		count++
	}
	formatted, err := format.Source(out.Bytes())
	must(err)
	must(os.WriteFile(target, formatted, 0644))
	fmt.Printf("Generated %d source scanner methods in %s\n", count, target)
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
