// Copyright (c) 2003 Compaq Corporation. All rights reserved.

package tlago

import "github.com/glycerine/tlago/tlc"

// sanySyntaxNodeImages ports SyntaxTreeConstants.SyntaxNodeImage in source
// index order. Images are distinct from the names of the node-kind constants.
var sanySyntaxNodeImages = [...]string{
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"Not a node",
	"N_ActDecl",
	"N_ActionExpr",
	"N_AssumeDecl",
	"N_AssumeProve",
	"N_Assumption",
	"N_BeginModule",
	"N_Body",
	"N_BoundedQuant",
	"N_Case",
	"N_CaseArm",
	"N_CaseStatement",
	"N_ChooseStatement",
	"N_ConjItem",
	"N_ConjList",
	"N_ConsDecl",
	"N_DisjItem",
	"N_DisjList",
	"N_EndModule",
	"N_Except",
	"N_ExceptComponent",
	"N_ExceptSpec",
	"N_Times",
	"N_Extends",
	"N_FairnessExpr",
	"N_FcnAppl",
	"N_FcnConst",
	"N_FieldSet",
	"N_FieldVal",
	"N_FunctionDefinition",
	"N_FunctionParam",
	"N_GeneralId",
	"N_GenInfixOp",
	"N_GenNonExpPrefixOp",
	"N_GenPostfixOp",
	"N_GenPrefixOp",
	"N_IdentDecl",
	"N_Real",
	"N_IdentifierTuple",
	"N_IdentLHS",
	"N_IdPrefix",
	"N_IdPrefixElement",
	"N_IfThenElse",
	"N_InfixDecl",
	"N_InfixExpr",
	"N_InfixLHS",
	"N_InfixOp",
	"N_InnerProof",
	"N_Instance",
	"N_NonLocalInstance",
	"N_Integer",
	"N_LeafProof",
	"N_LetDefinitions",
	"N_LetIn",
	"N_MaybeBound",
	"N_Module",
	"N_ModuleDefinition",
	"N_NonExpPrefixOp",
	"N_Number",
	"N_NumberedAssumeProve",
	"N_OpApplication",
	"N_OpArgs",
	"N_OperatorDefinition",
	"N_OtherArm",
	"N_ParamDecl",
	"N_ParamDeclaration",
	"N_ParenExpr",
	"N_PostfixDecl",
	"N_PostfixExpr",
	"N_PostfixLHS",
	"N_PostfixOp",
	"N_PrefixDecl",
	"N_PrefixExpr",
	"N_PrefixLHS",
	"N_PrefixOp",
	"N_Proof",
	"N_ProofLet",
	"N_ProofName",
	"N_ProofStatement",
	"N_ProofStep",
	"N_QEDStep",
	"N_QuantBound",
	"N_RcdConstructor",
	"N_RecordComponent",
	"N_SetEnumerate",
	"Not a node",
	"N_SetOfAll",
	"N_SetOfFcns",
	"N_SetOfRcds",
	"Not a node",
	"Not a node",
	"N_String",
	"N_SubsetOf",
	"N_Substitution",
	"N_TempDecl",
	"N_Theorem",
	"N_Tuple",
	"N_UnBoundedOrBoundedChoose",
	"N_UnboundedQuant",
	"N_VariableDeclaration",
	"Token =",
	"Token \\in",
	"N_NewSymb",
	"N_Lambda",
	"N_Recursive",
	"N_Label",
	"N_StructOp",
	"N_NumerableStep",
	"N_TerminalProof",
	"N_UseOrHide",
	"N_NonExprBody",
	"N_DefStep",
	"N_HaveStep",
	"N_TakeStep",
	"N_WitnessStep",
	"N_PickStep",
	"N_CaseStep",
	"N_AssertStep",
	"Not a node",
}

func sanySyntaxNodeImage(kind SanyNodeKind) string {
	index := int(kind)
	if index < 0 || index >= len(sanySyntaxNodeImages) {
		panic(tlc.NewArrayIndexOutOfBoundsException(index, len(sanySyntaxNodeImages)))
	}
	return sanySyntaxNodeImages[index]
}
