// Code generated by sany_generate_lookahead.go; DO NOT EDIT.
// Source: ../tlaplus/tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParser.java

package tlago

func (s *sanyLookahead) jj_3R_210() bool {
	if s.jj_3R_215() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_92() bool {
	if s.scanToken(SanyTokenKind(94)) {
		return true
	}
	if s.jj_3R_145() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_181() bool {
	if s.jj_3R_192() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_209() bool {
	if s.jj_3R_215() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_184() bool {
	if s.jj_3R_195() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_206() bool {
	if s.jj_3R_150() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_203() bool {
	if s.jj_3R_210() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_202() bool {
	if s.jj_3R_209() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_37() bool {
	if s.scanToken(SanyTokenKind(91)) {
		return true
	}
	if s.scanToken(SanyTokenKind(109)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_196() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_202() {
		s.position = xsp
		if s.jj_3R_203() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_171() bool {
	if s.scanToken(SanyTokenKind(109)) {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3_37() {
		s.position = xsp
	}
	return false
}

func (s *sanyLookahead) jj_3R_180() bool {
	if s.jj_3R_191() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_208() bool {
	if s.jj_3R_214() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_183() bool {
	if s.jj_3R_194() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_228() bool {
	if s.jj_3R_112() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_227() bool {
	if s.jj_3R_57() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_223() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_227() {
		s.position = xsp
		if s.jj_3R_228() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_205() bool {
	if s.jj_3R_212() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_104() bool {
	if s.scanToken(SanyTokenKind(110)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_219() bool {
	var xsp int
	if s.jj_3R_223() {
		return true
	}
	for {
		xsp = s.position
		if s.jj_3R_223() {
			s.position = xsp
			break
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_182() bool {
	if s.jj_3R_193() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_179() bool {
	if s.jj_3R_190() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_164() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_179() {
		s.position = xsp
		if s.jj_3R_180() {
			s.position = xsp
			if s.jj_3R_181() {
				s.position = xsp
				if s.jj_3R_182() {
					s.position = xsp
					if s.jj_3R_183() {
						s.position = xsp
						if s.jj_3R_184() {
							return true
						}
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_194() bool {
	if s.scanToken(SanyTokenKind(52)) {
		return true
	}
	if s.jj_3R_219() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_207() bool {
	if s.jj_3R_213() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_204() bool {
	if s.jj_3R_211() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_197() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_204() {
		s.position = xsp
		if s.jj_3R_205() {
			s.position = xsp
			if s.jj_3R_206() {
				s.position = xsp
				if s.jj_3R_207() {
					s.position = xsp
					if s.jj_3R_208() {
						return true
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_65() bool {
	if s.scanToken(SanyTokenKind(289)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_99() bool {
	if s.jj_3R_62() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_63() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(128)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(129)) {
			s.position = xsp
			if s.scanToken(SanyTokenKind(130)) {
				s.position = xsp
				if s.scanToken(SanyTokenKind(131)) {
					s.position = xsp
					if s.scanToken(SanyTokenKind(132)) {
						s.position = xsp
						if s.scanToken(SanyTokenKind(133)) {
							s.position = xsp
							if s.scanToken(SanyTokenKind(134)) {
								s.position = xsp
								if s.scanToken(SanyTokenKind(135)) {
									s.position = xsp
									if s.scanToken(SanyTokenKind(136)) {
										s.position = xsp
										if s.scanToken(SanyTokenKind(137)) {
											s.position = xsp
											if s.scanToken(SanyTokenKind(138)) {
												s.position = xsp
												if s.scanToken(SanyTokenKind(139)) {
													s.position = xsp
													if s.scanToken(SanyTokenKind(140)) {
														s.position = xsp
														if s.scanToken(SanyTokenKind(141)) {
															s.position = xsp
															if s.scanToken(SanyTokenKind(142)) {
																s.position = xsp
																if s.scanToken(SanyTokenKind(143)) {
																	s.position = xsp
																	if s.scanToken(SanyTokenKind(144)) {
																		s.position = xsp
																		if s.scanToken(SanyTokenKind(145)) {
																			s.position = xsp
																			if s.scanToken(SanyTokenKind(146)) {
																				s.position = xsp
																				if s.scanToken(SanyTokenKind(147)) {
																					s.position = xsp
																					if s.scanToken(SanyTokenKind(148)) {
																						s.position = xsp
																						if s.scanToken(SanyTokenKind(149)) {
																							s.position = xsp
																							if s.scanToken(SanyTokenKind(150)) {
																								s.position = xsp
																								if s.scanToken(SanyTokenKind(151)) {
																									s.position = xsp
																									if s.scanToken(SanyTokenKind(152)) {
																										s.position = xsp
																										if s.scanToken(SanyTokenKind(153)) {
																											s.position = xsp
																											if s.scanToken(SanyTokenKind(154)) {
																												s.position = xsp
																												if s.scanToken(SanyTokenKind(155)) {
																													s.position = xsp
																													if s.scanToken(SanyTokenKind(156)) {
																														s.position = xsp
																														if s.scanToken(SanyTokenKind(157)) {
																															s.position = xsp
																															if s.scanToken(SanyTokenKind(158)) {
																																s.position = xsp
																																if s.scanToken(SanyTokenKind(159)) {
																																	s.position = xsp
																																	if s.scanToken(SanyTokenKind(160)) {
																																		s.position = xsp
																																		if s.scanToken(SanyTokenKind(161)) {
																																			s.position = xsp
																																			if s.scanToken(SanyTokenKind(162)) {
																																				s.position = xsp
																																				if s.scanToken(SanyTokenKind(163)) {
																																					s.position = xsp
																																					if s.scanToken(SanyTokenKind(164)) {
																																						s.position = xsp
																																						if s.scanToken(SanyTokenKind(165)) {
																																							s.position = xsp
																																							if s.scanToken(SanyTokenKind(166)) {
																																								s.position = xsp
																																								if s.scanToken(SanyTokenKind(167)) {
																																									s.position = xsp
																																									if s.scanToken(SanyTokenKind(168)) {
																																										s.position = xsp
																																										if s.scanToken(SanyTokenKind(169)) {
																																											s.position = xsp
																																											if s.scanToken(SanyTokenKind(170)) {
																																												s.position = xsp
																																												if s.scanToken(SanyTokenKind(171)) {
																																													s.position = xsp
																																													if s.scanToken(SanyTokenKind(172)) {
																																														s.position = xsp
																																														if s.scanToken(SanyTokenKind(173)) {
																																															s.position = xsp
																																															if s.scanToken(SanyTokenKind(174)) {
																																																s.position = xsp
																																																if s.scanToken(SanyTokenKind(175)) {
																																																	s.position = xsp
																																																	if s.scanToken(SanyTokenKind(176)) {
																																																		s.position = xsp
																																																		if s.scanToken(SanyTokenKind(177)) {
																																																			s.position = xsp
																																																			if s.scanToken(SanyTokenKind(178)) {
																																																				s.position = xsp
																																																				if s.scanToken(SanyTokenKind(179)) {
																																																					s.position = xsp
																																																					if s.scanToken(SanyTokenKind(180)) {
																																																						s.position = xsp
																																																						if s.scanToken(SanyTokenKind(181)) {
																																																							s.position = xsp
																																																							if s.scanToken(SanyTokenKind(182)) {
																																																								s.position = xsp
																																																								if s.scanToken(SanyTokenKind(183)) {
																																																									s.position = xsp
																																																									if s.scanToken(SanyTokenKind(184)) {
																																																										s.position = xsp
																																																										if s.scanToken(SanyTokenKind(185)) {
																																																											s.position = xsp
																																																											if s.scanToken(SanyTokenKind(186)) {
																																																												s.position = xsp
																																																												if s.scanToken(SanyTokenKind(187)) {
																																																													s.position = xsp
																																																													if s.scanToken(SanyTokenKind(188)) {
																																																														s.position = xsp
																																																														if s.scanToken(SanyTokenKind(189)) {
																																																															s.position = xsp
																																																															if s.scanToken(SanyTokenKind(190)) {
																																																																s.position = xsp
																																																																if s.scanToken(SanyTokenKind(191)) {
																																																																	s.position = xsp
																																																																	if s.scanToken(SanyTokenKind(192)) {
																																																																		s.position = xsp
																																																																		if s.scanToken(SanyTokenKind(193)) {
																																																																			s.position = xsp
																																																																			if s.scanToken(SanyTokenKind(194)) {
																																																																				s.position = xsp
																																																																				if s.scanToken(SanyTokenKind(195)) {
																																																																					s.position = xsp
																																																																					if s.scanToken(SanyTokenKind(196)) {
																																																																						s.position = xsp
																																																																						if s.scanToken(SanyTokenKind(197)) {
																																																																							s.position = xsp
																																																																							if s.scanToken(SanyTokenKind(198)) {
																																																																								s.position = xsp
																																																																								if s.scanToken(SanyTokenKind(199)) {
																																																																									s.position = xsp
																																																																									if s.scanToken(SanyTokenKind(200)) {
																																																																										s.position = xsp
																																																																										if s.scanToken(SanyTokenKind(201)) {
																																																																											s.position = xsp
																																																																											if s.scanToken(SanyTokenKind(202)) {
																																																																												s.position = xsp
																																																																												if s.scanToken(SanyTokenKind(203)) {
																																																																													s.position = xsp
																																																																													if s.scanToken(SanyTokenKind(204)) {
																																																																														s.position = xsp
																																																																														if s.scanToken(SanyTokenKind(205)) {
																																																																															s.position = xsp
																																																																															if s.scanToken(SanyTokenKind(206)) {
																																																																																s.position = xsp
																																																																																if s.scanToken(SanyTokenKind(207)) {
																																																																																	s.position = xsp
																																																																																	if s.scanToken(SanyTokenKind(208)) {
																																																																																		s.position = xsp
																																																																																		if s.scanToken(SanyTokenKind(209)) {
																																																																																			s.position = xsp
																																																																																			if s.scanToken(SanyTokenKind(210)) {
																																																																																				s.position = xsp
																																																																																				if s.scanToken(SanyTokenKind(211)) {
																																																																																					s.position = xsp
																																																																																					if s.scanToken(SanyTokenKind(212)) {
																																																																																						s.position = xsp
																																																																																						if s.scanToken(SanyTokenKind(213)) {
																																																																																							s.position = xsp
																																																																																							if s.scanToken(SanyTokenKind(214)) {
																																																																																								s.position = xsp
																																																																																								if s.scanToken(SanyTokenKind(215)) {
																																																																																									s.position = xsp
																																																																																									if s.scanToken(SanyTokenKind(216)) {
																																																																																										s.position = xsp
																																																																																										if s.scanToken(SanyTokenKind(217)) {
																																																																																											s.position = xsp
																																																																																											if s.scanToken(SanyTokenKind(218)) {
																																																																																												s.position = xsp
																																																																																												if s.scanToken(SanyTokenKind(219)) {
																																																																																													s.position = xsp
																																																																																													if s.scanToken(SanyTokenKind(220)) {
																																																																																														s.position = xsp
																																																																																														if s.scanToken(SanyTokenKind(221)) {
																																																																																															s.position = xsp
																																																																																															if s.scanToken(SanyTokenKind(222)) {
																																																																																																s.position = xsp
																																																																																																if s.scanToken(SanyTokenKind(223)) {
																																																																																																	s.position = xsp
																																																																																																	if s.scanToken(SanyTokenKind(224)) {
																																																																																																		s.position = xsp
																																																																																																		if s.scanToken(SanyTokenKind(225)) {
																																																																																																			s.position = xsp
																																																																																																			if s.scanToken(SanyTokenKind(226)) {
																																																																																																				s.position = xsp
																																																																																																				if s.scanToken(SanyTokenKind(227)) {
																																																																																																					s.position = xsp
																																																																																																					if s.scanToken(SanyTokenKind(228)) {
																																																																																																						s.position = xsp
																																																																																																						if s.scanToken(SanyTokenKind(229)) {
																																																																																																							s.position = xsp
																																																																																																							if s.scanToken(SanyTokenKind(230)) {
																																																																																																								s.position = xsp
																																																																																																								if s.scanToken(SanyTokenKind(231)) {
																																																																																																									s.position = xsp
																																																																																																									if s.scanToken(SanyTokenKind(232)) {
																																																																																																										s.position = xsp
																																																																																																										if s.scanToken(SanyTokenKind(233)) {
																																																																																																											s.position = xsp
																																																																																																											if s.scanToken(SanyTokenKind(234)) {
																																																																																																												s.position = xsp
																																																																																																												if s.scanToken(SanyTokenKind(235)) {
																																																																																																													s.position = xsp
																																																																																																													if s.scanToken(SanyTokenKind(236)) {
																																																																																																														s.position = xsp
																																																																																																														if s.scanToken(SanyTokenKind(237)) {
																																																																																																															s.position = xsp
																																																																																																															if s.scanToken(SanyTokenKind(238)) {
																																																																																																																s.position = xsp
																																																																																																																if s.scanToken(SanyTokenKind(239)) {
																																																																																																																	s.position = xsp
																																																																																																																	if s.scanToken(SanyTokenKind(240)) {
																																																																																																																		s.position = xsp
																																																																																																																		if s.scanToken(SanyTokenKind(241)) {
																																																																																																																			s.position = xsp
																																																																																																																			if s.scanToken(SanyTokenKind(242)) {
																																																																																																																				s.position = xsp
																																																																																																																				if s.scanToken(SanyTokenKind(243)) {
																																																																																																																					s.position = xsp
																																																																																																																					if s.scanToken(SanyTokenKind(244)) {
																																																																																																																						s.position = xsp
																																																																																																																						if s.scanToken(SanyTokenKind(245)) {
																																																																																																																							s.position = xsp
																																																																																																																							if s.scanToken(SanyTokenKind(246)) {
																																																																																																																								s.position = xsp
																																																																																																																								if s.scanToken(SanyTokenKind(247)) {
																																																																																																																									s.position = xsp
																																																																																																																									if s.scanToken(SanyTokenKind(248)) {
																																																																																																																										s.position = xsp
																																																																																																																										if s.scanToken(SanyTokenKind(249)) {
																																																																																																																											s.position = xsp
																																																																																																																											if s.scanToken(SanyTokenKind(250)) {
																																																																																																																												s.position = xsp
																																																																																																																												if s.scanToken(SanyTokenKind(251)) {
																																																																																																																													s.position = xsp
																																																																																																																													if s.scanToken(SanyTokenKind(252)) {
																																																																																																																														s.position = xsp
																																																																																																																														if s.scanToken(SanyTokenKind(253)) {
																																																																																																																															s.position = xsp
																																																																																																																															if s.scanToken(SanyTokenKind(254)) {
																																																																																																																																s.position = xsp
																																																																																																																																if s.scanToken(SanyTokenKind(255)) {
																																																																																																																																	s.position = xsp
																																																																																																																																	if s.scanToken(SanyTokenKind(256)) {
																																																																																																																																		s.position = xsp
																																																																																																																																		if s.scanToken(SanyTokenKind(257)) {
																																																																																																																																			s.position = xsp
																																																																																																																																			if s.scanToken(SanyTokenKind(258)) {
																																																																																																																																				s.position = xsp
																																																																																																																																				if s.scanToken(SanyTokenKind(259)) {
																																																																																																																																					s.position = xsp
																																																																																																																																					if s.scanToken(SanyTokenKind(260)) {
																																																																																																																																						s.position = xsp
																																																																																																																																						if s.scanToken(SanyTokenKind(261)) {
																																																																																																																																							s.position = xsp
																																																																																																																																							if s.scanToken(SanyTokenKind(262)) {
																																																																																																																																								s.position = xsp
																																																																																																																																								if s.scanToken(SanyTokenKind(263)) {
																																																																																																																																									s.position = xsp
																																																																																																																																									if s.scanToken(SanyTokenKind(264)) {
																																																																																																																																										s.position = xsp
																																																																																																																																										if s.scanToken(SanyTokenKind(265)) {
																																																																																																																																											s.position = xsp
																																																																																																																																											if s.scanToken(SanyTokenKind(266)) {
																																																																																																																																												s.position = xsp
																																																																																																																																												if s.scanToken(SanyTokenKind(267)) {
																																																																																																																																													s.position = xsp
																																																																																																																																													if s.scanToken(SanyTokenKind(268)) {
																																																																																																																																														s.position = xsp
																																																																																																																																														if s.scanToken(SanyTokenKind(269)) {
																																																																																																																																															s.position = xsp
																																																																																																																																															if s.scanToken(SanyTokenKind(270)) {
																																																																																																																																																s.position = xsp
																																																																																																																																																if s.scanToken(SanyTokenKind(271)) {
																																																																																																																																																	s.position = xsp
																																																																																																																																																	if s.scanToken(SanyTokenKind(272)) {
																																																																																																																																																		s.position = xsp
																																																																																																																																																		if s.scanToken(SanyTokenKind(273)) {
																																																																																																																																																			s.position = xsp
																																																																																																																																																			if s.scanToken(SanyTokenKind(274)) {
																																																																																																																																																				s.position = xsp
																																																																																																																																																				if s.scanToken(SanyTokenKind(275)) {
																																																																																																																																																					s.position = xsp
																																																																																																																																																					if s.scanToken(SanyTokenKind(276)) {
																																																																																																																																																						s.position = xsp
																																																																																																																																																						if s.scanToken(SanyTokenKind(277)) {
																																																																																																																																																							s.position = xsp
																																																																																																																																																							if s.scanToken(SanyTokenKind(278)) {
																																																																																																																																																								s.position = xsp
																																																																																																																																																								if s.scanToken(SanyTokenKind(279)) {
																																																																																																																																																									s.position = xsp
																																																																																																																																																									if s.scanToken(SanyTokenKind(280)) {
																																																																																																																																																										s.position = xsp
																																																																																																																																																										if s.scanToken(SanyTokenKind(281)) {
																																																																																																																																																											s.position = xsp
																																																																																																																																																											if s.scanToken(SanyTokenKind(282)) {
																																																																																																																																																												s.position = xsp
																																																																																																																																																												if s.scanToken(SanyTokenKind(283)) {
																																																																																																																																																													s.position = xsp
																																																																																																																																																													if s.scanToken(SanyTokenKind(284)) {
																																																																																																																																																														s.position = xsp
																																																																																																																																																														if s.scanToken(SanyTokenKind(285)) {
																																																																																																																																																															s.position = xsp
																																																																																																																																																															if s.scanToken(SanyTokenKind(286)) {
																																																																																																																																																																s.position = xsp
																																																																																																																																																																if s.scanToken(SanyTokenKind(287)) {
																																																																																																																																																																	s.position = xsp
																																																																																																																																																																	if s.scanToken(SanyTokenKind(288)) {
																																																																																																																																																																		return true
																																																																																																																																																																	}
																																																																																																																																																																}
																																																																																																																																																															}
																																																																																																																																																														}
																																																																																																																																																													}
																																																																																																																																																												}
																																																																																																																																																											}
																																																																																																																																																										}
																																																																																																																																																									}
																																																																																																																																																								}
																																																																																																																																																							}
																																																																																																																																																						}
																																																																																																																																																					}
																																																																																																																																																				}
																																																																																																																																																			}
																																																																																																																																																		}
																																																																																																																																																	}
																																																																																																																																																}
																																																																																																																																															}
																																																																																																																																														}
																																																																																																																																													}
																																																																																																																																												}
																																																																																																																																											}
																																																																																																																																										}
																																																																																																																																									}
																																																																																																																																								}
																																																																																																																																							}
																																																																																																																																						}
																																																																																																																																					}
																																																																																																																																				}
																																																																																																																																			}
																																																																																																																																		}
																																																																																																																																	}
																																																																																																																																}
																																																																																																																															}
																																																																																																																														}
																																																																																																																													}
																																																																																																																												}
																																																																																																																											}
																																																																																																																										}
																																																																																																																									}
																																																																																																																								}
																																																																																																																							}
																																																																																																																						}
																																																																																																																					}
																																																																																																																				}
																																																																																																																			}
																																																																																																																		}
																																																																																																																	}
																																																																																																																}
																																																																																																															}
																																																																																																														}
																																																																																																													}
																																																																																																												}
																																																																																																											}
																																																																																																										}
																																																																																																									}
																																																																																																								}
																																																																																																							}
																																																																																																						}
																																																																																																					}
																																																																																																				}
																																																																																																			}
																																																																																																		}
																																																																																																	}
																																																																																																}
																																																																																															}
																																																																																														}
																																																																																													}
																																																																																												}
																																																																																											}
																																																																																										}
																																																																																									}
																																																																																								}
																																																																																							}
																																																																																						}
																																																																																					}
																																																																																				}
																																																																																			}
																																																																																		}
																																																																																	}
																																																																																}
																																																																															}
																																																																														}
																																																																													}
																																																																												}
																																																																											}
																																																																										}
																																																																									}
																																																																								}
																																																																							}
																																																																						}
																																																																					}
																																																																				}
																																																																			}
																																																																		}
																																																																	}
																																																																}
																																																															}
																																																														}
																																																													}
																																																												}
																																																											}
																																																										}
																																																									}
																																																								}
																																																							}
																																																						}
																																																					}
																																																				}
																																																			}
																																																		}
																																																	}
																																																}
																																															}
																																														}
																																													}
																																												}
																																											}
																																										}
																																									}
																																								}
																																							}
																																						}
																																					}
																																				}
																																			}
																																		}
																																	}
																																}
																															}
																														}
																													}
																												}
																											}
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_101() bool {
	if s.jj_3R_63() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_218() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_151() bool {
	if s.jj_3R_141() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_141() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(118)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(119)) {
			s.position = xsp
			if s.scanToken(SanyTokenKind(120)) {
				s.position = xsp
				if s.scanToken(SanyTokenKind(121)) {
					s.position = xsp
					if s.scanToken(SanyTokenKind(122)) {
						s.position = xsp
						if s.scanToken(SanyTokenKind(117)) {
							s.position = xsp
							if s.scanToken(SanyTokenKind(123)) {
								s.position = xsp
								if s.scanToken(SanyTokenKind(124)) {
									s.position = xsp
									if s.scanToken(SanyTokenKind(125)) {
										s.position = xsp
										if s.scanToken(SanyTokenKind(126)) {
											s.position = xsp
											if s.scanToken(SanyTokenKind(127)) {
												return true
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_178() bool {
	if s.jj_3R_146() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_193() bool {
	if s.scanToken(SanyTokenKind(42)) {
		return true
	}
	if s.jj_3R_218() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_146() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(118)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(119)) {
			s.position = xsp
			if s.scanToken(SanyTokenKind(120)) {
				s.position = xsp
				if s.scanToken(SanyTokenKind(121)) {
					s.position = xsp
					if s.scanToken(SanyTokenKind(122)) {
						s.position = xsp
						if s.scanToken(SanyTokenKind(123)) {
							s.position = xsp
							if s.scanToken(SanyTokenKind(124)) {
								s.position = xsp
								if s.scanToken(SanyTokenKind(125)) {
									s.position = xsp
									if s.scanToken(SanyTokenKind(126)) {
										s.position = xsp
										if s.scanToken(SanyTokenKind(127)) {
											return true
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_192() bool {
	if s.scanToken(SanyTokenKind(50)) {
		return true
	}
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_214() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(86)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(59)) {
			return true
		}
	}
	if s.jj_3R_235() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_243() bool {
	if s.jj_3R_213() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_242() bool {
	if s.jj_3R_150() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_241() bool {
	if s.jj_3R_212() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_240() bool {
	if s.jj_3R_211() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_239() bool {
	if s.jj_3R_244() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_235() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_239() {
		s.position = xsp
		if s.jj_3R_240() {
			s.position = xsp
			if s.jj_3R_241() {
				s.position = xsp
				if s.jj_3R_242() {
					s.position = xsp
					if s.jj_3R_243() {
						return true
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_167() bool {
	if s.scanToken(SanyTokenKind(92)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_166() bool {
	if s.jj_3R_151() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_131() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_166() {
		s.position = xsp
		if s.jj_3R_167() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_130() bool {
	if s.scanToken(SanyTokenKind(94)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_66() bool {
	if s.jj_3R_65() {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3R_130() {
		s.position = xsp
	}
	return false
}

func (s *sanyLookahead) jj_3R_244() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_158() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_234() bool {
	if s.scanToken(SanyTokenKind(103)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_233() bool {
	if s.scanToken(SanyTokenKind(104)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_49() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_213() bool {
	if s.scanToken(SanyTokenKind(102)) {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3_49() {
		s.position = xsp
	}
	xsp = s.position
	if s.jj_3R_233() {
		s.position = xsp
		if s.jj_3R_234() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_159() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_161() bool {
	if s.jj_3R_141() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_160() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_187() bool {
	if s.scanToken(SanyTokenKind(88)) {
		return true
	}
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_169() bool {
	if s.jj_3R_65() {
		return true
	}
	var xsp int
	for {
		xsp = s.position
		if s.jj_3R_187() {
			s.position = xsp
			break
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_142() bool {
	if s.scanToken(SanyTokenKind(102)) {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3R_169() {
		s.position = xsp
	}
	if s.scanToken(SanyTokenKind(104)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_238() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_120() bool {
	if s.jj_3R_161() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_237() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_119() bool {
	if s.jj_3R_160() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_236() bool {
	if s.scanToken(SanyTokenKind(105)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_118() bool {
	if s.jj_3R_159() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_117() bool {
	if s.jj_3R_158() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_48() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_232() bool {
	if s.jj_3R_238() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_116() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_115() bool {
	if s.scanToken(SanyTokenKind(54)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_231() bool {
	if s.jj_3R_237() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_57() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_115() {
		s.position = xsp
	}
	if s.scanToken(SanyTokenKind(96)) {
		return true
	}
	xsp = s.position
	if s.jj_3R_116() {
		s.position = xsp
		if s.jj_3R_117() {
			s.position = xsp
			if s.jj_3R_118() {
				s.position = xsp
				if s.jj_3R_119() {
					s.position = xsp
					if s.jj_3R_120() {
						return true
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_230() bool {
	if s.jj_3R_237() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_229() bool {
	if s.jj_3R_222() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_150() bool {
	var semLA bool

	if s.scanToken(SanyTokenKind(97)) {
		return true
	}
	var xsp int
	xsp = s.position
	semLA = s.matchFcnConst()
	if !semLA || s.jj_3R_229() {
		s.position = xsp
		if s.jj_3R_230() {
			s.position = xsp
			semLA = (s.token(2).Kind == SanyTokenKind(108)) && isSanyFieldNameToken(s.token(1).Kind)
			if !semLA || s.jj_3R_231() {
				s.position = xsp
				if s.jj_3R_232() {
					s.position = xsp
					if s.jj_3_48() {
						return true
					}
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3_44() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_224() bool {
	if s.jj_3R_236() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_91() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_68() bool {
	if s.jj_3R_92() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_176() bool {
	if s.jj_3R_151() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_175() bool {
	if s.jj_3R_99() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_90() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_174() bool {
	if s.jj_3R_101() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_112() bool {
	if s.scanToken(SanyTokenKind(79)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_173() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(290)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(291)) {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_172() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_149() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_172() {
		s.position = xsp
		if s.jj_3R_173() {
			s.position = xsp
			if s.jj_3R_174() {
				s.position = xsp
				if s.jj_3R_175() {
					s.position = xsp
					if s.jj_3R_176() {
						return true
					}
				}
			}
		}
	}
	xsp = s.position
	if s.jj_3_68() {
		s.position = xsp
	}
	for {
		xsp = s.position
		if s.jj_3R_224() {
			s.position = xsp
			break
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_144() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_148() bool {
	if s.jj_3R_171() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_147() bool {
	if s.jj_3R_104() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_95() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
	if !semLA || s.jj_3R_147() {
		s.position = xsp
		semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
		if !semLA || s.jj_3R_148() {
			s.position = xsp
			if s.jj_3R_149() {
				return true
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_143() bool {
	if s.jj_3R_142() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_89() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_143() {
		s.position = xsp
		if s.jj_3R_144() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3_45() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	semLA = s.matchFcnConst()
	if !semLA || s.jj_3R_89() {
		s.position = xsp
		if s.jj_3R_90() {
			s.position = xsp
			if s.jj_3R_91() {
				s.position = xsp
				if s.jj_3_44() {
					return true
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_212() bool {
	if s.scanToken(SanyTokenKind(100)) {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3_45() {
		s.position = xsp
	}
	if s.scanToken(SanyTokenKind(101)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_103() bool {
	if s.scanToken(SanyTokenKind(90)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_226() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_225() bool {
	if s.jj_3R_142() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_222() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_225() {
		s.position = xsp
		if s.jj_3R_226() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_191() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(60)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(61)) {
			return true
		}
	}
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_102() bool {
	if s.jj_3R_101() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_66() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
	if !semLA || s.jj_3R_102() {
		s.position = xsp
		semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
		if !semLA || s.jj_3R_103() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_75() bool {
	return false
}

func (s *sanyLookahead) jj_3_22() bool {
	var semLA bool

	semLA = s.token(1).Kind == SanyTokenKind(39) || s.token(1).Kind == SanyTokenKind(40)
	if !semLA || s.jj_3R_75() {
		return true
	}
	if s.jj_3R_76() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_217() bool {
	if s.jj_3R_222() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_98() bool {
	if s.jj_3R_150() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_216() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_190() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(47)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(49)) {
			return true
		}
	}
	xsp = s.position
	if s.jj_3R_216() {
		s.position = xsp
		if s.jj_3R_217() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_97() bool {
	if s.scanToken(SanyTokenKind(91)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_96() bool {
	if s.jj_3R_99() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_58() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
	if !semLA || s.jj_3R_96() {
		s.position = xsp
		semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
		if !semLA || s.jj_3R_97() {
			s.position = xsp
			semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
			if !semLA || s.jj_3R_98() {
				return true
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3_57() bool {
	if s.jj_3R_95() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_211() bool {
	if s.scanToken(SanyTokenKind(94)) {
		return true
	}
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_186() bool {
	if s.jj_3R_197() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_145() bool {
	if s.jj_3R_170() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_185() bool {
	if s.jj_3R_196() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_74() bool {
	if s.jj_3R_131() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_73() bool {
	if s.jj_3R_66() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_165() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	semLA = s.preInEmptyTop()
	if !semLA || s.jj_3R_185() {
		s.position = xsp
		if s.jj_3R_186() {
			s.position = xsp
			if s.jj_3_57() {
				return true
			}
		}
	}
	for {
		xsp = s.position
		if s.jj_3_58() {
			s.position = xsp
			break
		}
	}
	xsp = s.position
	if s.jj_3_66() {
		s.position = xsp
	}
	return false
}

func (s *sanyLookahead) jj_3R_72() bool {
	if s.scanToken(SanyTokenKind(56)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_40() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_20() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_72() {
		s.position = xsp
	}
	xsp = s.position
	if s.scanToken(SanyTokenKind(80)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(38)) {
			s.position = xsp
			if s.scanToken(SanyTokenKind(81)) {
				return true
			}
		}
	}
	xsp = s.position
	if s.jj_3R_73() {
		s.position = xsp
		if s.jj_3R_74() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_189() bool {
	if s.jj_3R_201() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_200() bool {
	if s.jj_3R_99() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_71() bool {
	if s.scanToken(SanyTokenKind(56)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_70() bool {
	if s.jj_3R_131() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_19() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_71() {
		s.position = xsp
	}
	if s.scanToken(SanyTokenKind(85)) {
		return true
	}
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_199() bool {
	if s.jj_3R_101() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_198() bool {
	if s.jj_3R_151() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_125() bool {
	if s.jj_3R_165() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_67() bool {
	if s.scanToken(SanyTokenKind(147)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_124() bool {
	if s.jj_3R_164() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_17() bool {
	if s.jj_3R_66() {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3R_67() {
		s.position = xsp
	}
	return false
}

func (s *sanyLookahead) jj_3R_69() bool {
	if s.scanToken(SanyTokenKind(44)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_188() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_198() {
		s.position = xsp
		if s.jj_3R_199() {
			s.position = xsp
			if s.jj_3R_200() {
				return true
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_68() bool {
	if s.scanToken(SanyTokenKind(56)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_170() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
	if !semLA || s.jj_3R_188() {
		s.position = xsp
		semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
		if !semLA || s.jj_3R_189() {
			s.position = xsp
			if s.jj_3_40() {
				return true
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3_16() bool {
	if s.scanToken(SanyTokenKind(56)) {
		return true
	}
	if s.scanToken(SanyTokenKind(44)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_163() bool {
	if s.jj_3R_101() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_62() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(113)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(114)) {
			s.position = xsp
			if s.scanToken(SanyTokenKind(115)) {
				s.position = xsp
				if s.scanToken(SanyTokenKind(116)) {
					return true
				}
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_162() bool {
	if s.jj_3R_178() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_18() bool {
	var xsp int
	xsp = s.position
	if s.jj_3_16() {
		s.position = xsp
		if s.jj_3R_68() {
			s.position = xsp
			if s.jj_3R_69() {
				return true
			}
		}
	}
	xsp = s.position
	if s.jj_3_17() {
		s.position = xsp
		if s.jj_3R_70() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_123() bool {
	var xsp int
	xsp = s.position
	if s.jj_3R_162() {
		s.position = xsp
		if s.jj_3R_163() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_168() bool {
	var xsp int
	xsp = s.position
	if s.jj_3_18() {
		s.position = xsp
		if s.jj_3_19() {
			s.position = xsp
			if s.jj_3_20() {
				return true
			}
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_61() bool {
	var semLA bool

	var xsp int
	for {
		xsp = s.position
		if s.jj_3R_123() {
			s.position = xsp
			break
		}
	}
	xsp = s.position
	semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
	if !semLA || s.jj_3R_124() {
		s.position = xsp
		semLA = s.parser.junctionListContext.isAboveCurrent(s.token(1).Begin.Column)
		if !semLA || s.jj_3R_125() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_201() bool {
	if s.scanToken(SanyTokenKind(73)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_135() bool {
	if s.scanToken(SanyTokenKind(88)) {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3_14() bool {
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_134() bool {
	if s.jj_3R_168() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_221() bool {
	if s.jj_3R_142() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_220() bool {
	if s.jj_3R_65() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_195() bool {
	if s.scanToken(SanyTokenKind(43)) {
		return true
	}
	var xsp int
	xsp = s.position
	if s.jj_3R_220() {
		s.position = xsp
		if s.jj_3R_221() {
			return true
		}
	}
	return false
}

func (s *sanyLookahead) jj_3R_133() bool {
	if s.jj_3R_76() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_215() bool {
	var xsp int
	xsp = s.position
	if s.scanToken(SanyTokenKind(132)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(129)) {
			return true
		}
	}
	if s.jj_3R_61() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_132() bool {
	if s.jj_3R_65() {
		return true
	}
	if s.scanToken(SanyTokenKind(90)) {
		return true
	}
	if s.jj_3R_76() {
		return true
	}
	return false
}

func (s *sanyLookahead) jj_3R_76() bool {
	var semLA bool

	var xsp int
	xsp = s.position
	if s.jj_3R_132() {
		s.position = xsp
	}
	xsp = s.position
	if s.scanToken(SanyTokenKind(39)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(40)) {
			return true
		}
	}
	xsp = s.position
	semLA = (s.token(1).Kind == SanyTokenKind(39) || s.token(1).Kind == SanyTokenKind(40)) || ((s.token(2).Kind == SanyTokenKind(90)) && (s.token(3).Kind == SanyTokenKind(39) || s.token(3).Kind == SanyTokenKind(40)))
	if !semLA || s.jj_3R_133() {
		s.position = xsp
		if s.jj_3R_134() {
			s.position = xsp
			if s.jj_3_14() {
				return true
			}
		}
	}
	for {
		xsp = s.position
		if s.jj_3R_135() {
			s.position = xsp
			break
		}
	}
	xsp = s.position
	if s.scanToken(SanyTokenKind(76)) {
		s.position = xsp
		if s.scanToken(SanyTokenKind(77)) {
			return true
		}
	}
	return false
}
