/*******************************************************************************
 * Copyright (c) 2021 Microsoft Research. All rights reserved.
 *
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Softw//are.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Contributors:
 *   Markus Alexander Kuppe - initial API and implementation
 ******************************************************************************/
// Translation of the complete EchoDebuggerTest.testSpec and its inherited
// TLC frame, state-variable, trace, context and successor assertions.
package tlago

import (
	"strings"
	"testing"

	"github.com/glycerine/tlago/tlc"
)

func TestJavaEchoDebugger(t *testing.T) {
	const RM = "Echo"
	const MDL = "MCEcho"
	h := startJavaDebuggerModel(t, "Echo", "MCEcho", tlc.ExitStatusSuccess)
	defer h.close()
	stackFrames := h.frames()
	debuggerAssertEqual(t, 1, len(stackFrames))
	assertTLCFrame(t, stackFrames[0], 12, 21, RM)
	debuggerAssertTrue(t, strings.HasSuffix(strings.ReplaceAll(h.sourcePath(stackFrames[0]), "\\", "/"), "test_vectors/models/Echo/Echo.tla"))
	f := stackFrames[0].Base
	constants := f.GetConstants(nil)
	debuggerAssertEqual(t, 3, len(constants))
	debuggerAssertEqual(t, "Echo", constants[0].Name)
	nested := f.GetVariables(constants[0].VariablesReference, nil)
	debuggerAssertEqual(t, 4, len(nested))
	debuggerAssertEqual(t, "I1", nested[0].Name)
	debuggerAssertEqual(t, "a", nested[0].Value)
	debuggerAssertEqual(t, "N1", nested[1].Name)
	debuggerAssertEqual(t, "{\"a\", \"b\", \"c\"}", nested[1].Value)
	debuggerAssertEqual(t, "ProcSet", nested[2].Name)
	debuggerAssertEqual(t, "{\"a\", \"b\", \"c\"}", nested[2].Value)
	debuggerAssertEqual(t, "R1", nested[3].Name)
	debuggerAssertEqual(t, "(<<\"a\", \"a\">> :> FALSE @@ <<\"a\", \"b\">> :> TRUE @@ <<\"a\", \"c\">> :> TRUE @@ <<\"b\", \"a\">> :> TRUE @@ <<\"b\", \"b\">> :> FALSE @@ <<\"b\", \"c\">> :> TRUE @@ <<\"c\", \"a\">> :> TRUE @@ <<\"c\", \"b\">> :> TRUE @@ <<\"c\", \"c\">> :> FALSE)", nested[3].Value)
	debuggerAssertEqual(t, "MCEcho", constants[1].Name)
	nested = f.GetVariables(constants[1].VariablesReference, nil)
	debuggerAssertEqual(t, 4, len(nested))
	debuggerAssertEqual(t, "I1", nested[0].Name)
	debuggerAssertEqual(t, "a", nested[0].Value)
	debuggerAssertEqual(t, "N1", nested[1].Name)
	debuggerAssertEqual(t, "{\"a\", \"b\", \"c\"}", nested[1].Value)
	debuggerAssertEqual(t, "R1", nested[2].Name)
	debuggerAssertEqual(t, "(<<\"a\", \"a\">> :> FALSE @@ <<\"a\", \"b\">> :> TRUE @@ <<\"a\", \"c\">> :> TRUE @@ <<\"b\", \"a\">> :> TRUE @@ <<\"b\", \"b\">> :> FALSE @@ <<\"b\", \"c\">> :> TRUE @@ <<\"c\", \"a\">> :> TRUE @@ <<\"c\", \"b\">> :> TRUE @@ <<\"c\", \"c\">> :> FALSE)", nested[2].Value)
	debuggerAssertEqual(t, "R2", nested[3].Name)
	debuggerAssertEqual(t, "(<<\"a\", \"a\">> :> FALSE @@ <<\"a\", \"b\">> :> FALSE @@ <<\"a\", \"c\">> :> TRUE @@ <<\"b\", \"a\">> :> FALSE @@ <<\"b\", \"b\">> :> FALSE @@ <<\"b\", \"c\">> :> TRUE @@ <<\"c\", \"a\">> :> TRUE @@ <<\"c\", \"b\">> :> TRUE @@ <<\"c\", \"c\">> :> FALSE)", nested[3].Value)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 2, len(stackFrames))
	assertTLCFrame(t, stackFrames[1], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[0], 12, 11, 12, 28, RM)
	stackFrames = h.stepIn(2)
	debuggerAssertEqual(t, 4, len(stackFrames))
	assertTLCFrame(t, stackFrames[3], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[2], 12, 11, 12, 28, RM)
	assertTLCFrame(t, stackFrames[1], 12, 11, 12, 19, RM)
	assertTLCFrame(t, stackFrames[0], 9, 7, 9, 28, MDL)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 5, len(stackFrames))
	assertTLCFrame(t, stackFrames[4], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[3], 12, 11, 12, 28, RM)
	assertTLCFrame(t, stackFrames[2], 12, 11, 12, 19, RM)
	assertTLCFrame(t, stackFrames[1], 9, 7, 9, 28, MDL)
	assertTLCFrame(t, stackFrames[0], 9, 20, 9, 21, MDL)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 5, len(stackFrames))
	assertTLCFrame(t, stackFrames[4], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[3], 12, 11, 12, 28, RM)
	assertTLCFrame(t, stackFrames[2], 12, 11, 12, 19, RM)
	assertTLCFrame(t, stackFrames[1], 9, 7, 9, 28, MDL)
	assertTLCFrame(t, stackFrames[0], 9, 25, 9, 28, MDL, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")))
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 3, len(stackFrames))
	assertTLCFrame(t, stackFrames[2], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[1], 12, 11, 12, 28, RM)
	assertTLCFrame(t, stackFrames[0], 12, 25, 12, 28, RM)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 4, len(stackFrames))
	assertTLCFrame(t, stackFrames[3], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[2], 12, 11, 12, 28, RM)
	assertTLCFrame(t, stackFrames[1], 12, 25, 12, 28, RM)
	assertTLCFrame(t, stackFrames[0], 5, 7, 5, 21, MDL)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 2, len(stackFrames))
	assertTLCFrame(t, stackFrames[1], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[0], 13, 11, 13, 41, RM)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 3, len(stackFrames))
	assertTLCFrame(t, stackFrames[2], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[1], 13, 11, 13, 41, RM)
	assertTLCFrame(t, stackFrames[0], 13, 11, 13, 11, RM)
	stackFrames = h.stepIn()
	debuggerAssertEqual(t, 4, len(stackFrames))
	assertTLCFrame(t, stackFrames[3], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[2], 13, 11, 13, 41, RM)
	assertTLCFrame(t, stackFrames[1], 13, 11, 13, 11, RM)
	assertTLCFrame(t, stackFrames[0], 22, 7, 24, 43, MDL)
	stackFrames = h.stepOut()
	debuggerAssertEqual(t, 3, len(stackFrames))
	assertTLCFrame(t, stackFrames[2], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[1], 13, 11, 13, 41, RM)
	assertTLCFrame(t, stackFrames[0], 13, 11, 13, 11, RM)
	stackFrames = h.stepOut()
	debuggerAssertEqual(t, 2, len(stackFrames))
	assertTLCFrame(t, stackFrames[1], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[0], 13, 11, 13, 41, RM)
	stackFrames = h.next()
	debuggerAssertEqual(t, 2, len(stackFrames))
	assertTLCFrame(t, stackFrames[1], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[0], 15, 11, 15, 32, RM)
	stackFrames = h.next()
	debuggerAssertEqual(t, 2, len(stackFrames))
	assertTLCFrame(t, stackFrames[1], 12, 8, 21, 30, RM)
	assertTLCFrame(t, stackFrames[0], 15, 11, 15, 32, RM)
	h.replaceBreakpoints("Relation", 49)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 8, len(stackFrames))
	assertTLCFrame(t, stackFrames[0], 49, 3, 50, 38, "Relation", nil)
	assertTLCFrame(t, stackFrames[7], 12, 8, 21, 30, RM)
	h.replaceBreakpoints(RM, 167)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 13, len(stackFrames))
	assertTLCStateFrame(t, stackFrames[0], 167, 6, 167, 63, RM, tlc.EmptyContext)
	frame := stackFrames[0].State
	trace := frame.TraceVariables(nil)
	debuggerAssertEqual(t, 1, len(trace))
	debuggerAssertEqual(t, tlc.NewRecordValueFromState(frame.State), trace[0].TLCValue)
	debuggerAssertEqual(t, "1: <Init line 95, col 9 to line 101, col 43 of module Echo>", trace[len(trace)-1].Name)
	assertTLCSyntheticStateStackFrame(t, stackFrames[12], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	h.unsetBreakpoints()
	h.replaceBreakpoints(RM, 104)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 5, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 104, 16, 107, 40, RM, nil, tlc.StateVariables())
	assertTLCSyntheticStateStackFrame(t, stackFrames[4], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	h.replaceBreakpoints(RM, 167)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 11, len(stackFrames))
	assertTLCStateFrame(t, stackFrames[0], 167, 6, 167, 63, RM, tlc.EmptyContext)
	frame = stackFrames[0].State
	debuggerAssertEqual(t, 2, frame.State.Level())
	assertTLCSyntheticStateStackFrame(t, stackFrames[10], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	h.unsetBreakpoints()
	sba := debuggerBreakpoint(RM, 167, "NotNotTypeOK")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 12, len(stackFrames))
	assertTLCStateFrame(t, stackFrames[0], 167, 6, 167, 63, RM, tlc.EmptyContext)
	h.unsetBreakpoints()
	sba = debuggerBreakpoint(RM, 104)
	sba.requests[0].HitCondition = "5"
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 7, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 104, 16, 107, 40, RM, nil, tlc.StateVariables())
	assertTLCSyntheticStateStackFrame(t, stackFrames[4], 103, 13, 109, 59, RM, nil, 3)
	assertTLCSyntheticStateStackFrame(t, stackFrames[5], 103, 13, 109, 59, RM, nil, 2)
	assertTLCSyntheticStateStackFrame(t, stackFrames[6], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	sba = debuggerBreakpoint(RM, 103, "DebugExpression")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 5, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), tlc.StateVariables())
	sba = debuggerBreakpoint(RM, 103, "DebugExpression2")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 5, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")), tlc.StateVariables())
	sba = debuggerBreakpoint(RM, 112, 0, 13)
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 15, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 112, 16, 129, 71, RM, nil, tlc.StateVariables())
	sba = debuggerBreakpoint(RM, 133, "DebugExpression")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 15, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 133, 16, 138, 40, RM, nil, tlc.StateVariables())
	sba = debuggerBreakpoint(MDL, 38, "View")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 22, len(stackFrames))
	assertTLCStateFrame(t, stackFrames[0], 38, 9, 38, 12, MDL, tlc.EmptyContext)
	frame = stackFrames[0].State
	constants = frame.GetConstants(nil)
	nested = frame.GetVariables(constants[0].VariablesReference, nil)
	debuggerAssertEqual(t, 4, len(nested))
	debuggerAssertEqual(t, "I1", nested[0].Name)
	debuggerAssertEqual(t, "a", nested[0].Value)
	debuggerAssertEqual(t, "N1", nested[1].Name)
	debuggerAssertEqual(t, "{\"a\", \"b\", \"c\"}", nested[1].Value)
	debuggerAssertEqual(t, "ProcSet", nested[2].Name)
	debuggerAssertEqual(t, "{\"a\", \"b\", \"c\"}", nested[2].Value)
	debuggerAssertEqual(t, "R1", nested[3].Name)
	debuggerAssertEqual(t, "(<<\"a\", \"a\">> :> FALSE @@ <<\"a\", \"b\">> :> TRUE @@ <<\"a\", \"c\">> :> TRUE @@ <<\"b\", \"a\">> :> TRUE @@ <<\"b\", \"b\">> :> FALSE @@ <<\"b\", \"c\">> :> TRUE @@ <<\"c\", \"a\">> :> TRUE @@ <<\"c\", \"b\">> :> TRUE @@ <<\"c\", \"c\">> :> FALSE)", nested[3].Value)
	trace = frame.TraceVariables(nil)
	debuggerAssertEqual(t, 12, len(trace))
	debuggerAssertEqual(t, "1: <Init line 95, col 9 to line 101, col 43 of module Echo>", trace[len(trace)-1].Name)
	scopes := frame.GetScopes()
	debuggerAssertEqual(t, 4, len(scopes))
	stateScope := debuggerScope(t, scopes, "State")
	nested = h.debugger.Variables(stateScope.VariablesReference)
	debuggerAssertEqual(t, 1, len(nested))
	debuggerAssertEqual(t, tlc.NewRecordValueFromState(frame.State), nested[0].TLCValue)
	assertTLCSyntheticStateStackFrame(t, stackFrames[10], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")),
		12)
	assertTLCSyntheticStateStackFrame(t, stackFrames[11], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")),
		11)
	assertTLCSyntheticStateStackFrame(t, stackFrames[12], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")),
		10)
	assertTLCSyntheticStateStackFrame(t, stackFrames[13], 132, 13, 140, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 9)
	assertTLCSyntheticStateStackFrame(t, stackFrames[14], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 8)
	assertTLCSyntheticStateStackFrame(t, stackFrames[15], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 7)
	assertTLCSyntheticStateStackFrame(t, stackFrames[16], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 6)
	assertTLCSyntheticStateStackFrame(t, stackFrames[17], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 5)
	assertTLCSyntheticStateStackFrame(t, stackFrames[18], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 4)
	assertTLCSyntheticStateStackFrame(t, stackFrames[19], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 3)
	assertTLCSyntheticStateStackFrame(t, stackFrames[20], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")), 2)
	assertTLCSyntheticStateStackFrame(t, stackFrames[21], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	h.setSpecBreakpoint()
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 13, len(stackFrames))
	assertTLCNextStatesFrame(t, stackFrames[0], 151, 20, 151, 23, RM, tlc.EmptyContext, 1)
	assertTLCSyntheticStateStackFrame(t, stackFrames[1], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")),
		12)
	assertTLCSyntheticStateStackFrame(t, stackFrames[2], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")),
		11)
	assertTLCSyntheticStateStackFrame(t, stackFrames[3], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")),
		10)
	assertTLCSyntheticStateStackFrame(t, stackFrames[4], 132, 13, 140, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 9)
	assertTLCSyntheticStateStackFrame(t, stackFrames[5], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 8)
	assertTLCSyntheticStateStackFrame(t, stackFrames[6], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 7)
	assertTLCSyntheticStateStackFrame(t, stackFrames[7], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 6)
	assertTLCSyntheticStateStackFrame(t, stackFrames[8], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 5)
	assertTLCSyntheticStateStackFrame(t, stackFrames[9], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 4)
	assertTLCSyntheticStateStackFrame(t, stackFrames[10], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 3)
	assertTLCSyntheticStateStackFrame(t, stackFrames[11], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")), 2)
	assertTLCSyntheticStateStackFrame(t, stackFrames[12], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	h.unsetBreakpoints()
	sba = debuggerBreakpoint(RM, 133, 19, 1, "\\E n \\in Node: inbox[n] = {}")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 16, len(stackFrames))
	assertTLCActionFrame(t, stackFrames[0], 133, 19, 133, 34, RM, nil, tlc.StateVariables())
	assertTLCSyntheticStateStackFrame(t, stackFrames[5], 132, 13, 140, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")),
		11)
	assertTLCSyntheticStateStackFrame(t, stackFrames[6], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")),
		10)
	assertTLCSyntheticStateStackFrame(t, stackFrames[7], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 9)
	assertTLCSyntheticStateStackFrame(t, stackFrames[8], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 8)
	assertTLCSyntheticStateStackFrame(t, stackFrames[9], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 7)
	assertTLCSyntheticStateStackFrame(t, stackFrames[10], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 6)
	assertTLCSyntheticStateStackFrame(t, stackFrames[11], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")).Cons(nil, tlc.NewStringValue("c")), 5)
	assertTLCSyntheticStateStackFrame(t, stackFrames[12], 111, 13, 130, 27, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 4)
	assertTLCSyntheticStateStackFrame(t, stackFrames[13], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")).Cons(nil, tlc.NewStringValue("b")), 3)
	assertTLCSyntheticStateStackFrame(t, stackFrames[14], 103, 13, 109, 59, RM, tlc.EmptyContext.Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")).Cons(nil, tlc.NewStringValue("a")), 2)
	assertTLCSyntheticStateStackFrame(t, stackFrames[15], 95, 9, 101, 43, RM, tlc.EmptyContext, 1)
	h.unsetBreakpoints()
	sba = debuggerBreakpoint(RM, 140, 16, 1, "\\E n \\in Node: inbox'[n] = {}")
	h.setBreakpoints(sba)
	stackFrames = h.continueFrames()
	debuggerAssertEqual(t, 20, len(stackFrames))
	vars := tlc.StateVariables()
	assertTLCActionFrame(t, stackFrames[0], 140, 16, 140, 59, RM, nil, vars[1], vars[2], vars[3], vars[4])
	h.unsetBreakpoints()
	h.continueFrames()
}
